clc
clear all


CHECK_NEW=1;

DATAoffline.LABEL_DOMAIN = [1]; % LABEL IDENTIFYING THE SURFACE/VOLUME WE WISH TO STUDY
DATAoffline.LABELS_FACES =   [5,6,7,8];   % LABELS IDENTIFYING THE BOUNDARY OF SUCH A DOMAIN

NAMEMESH ='TRAININGdomEIFE' ; % % 'TRAININGdomP' ;
DATALOC.NameFileMeshDATA =[cd,filesep,'GIDPRE/',NAMEMESH,'.msh'] ;
BOUNDARY_CONDIDITONS = 'FBC_tensionX_EIFEM_70p' ;
%MATERIAL_FILE  = 'PlasticityMaterialDATA2mat' ;  'PlasticMaterialDATA_elas' ;
MAterialFile ='MATERIAL_EIFE_plast';
if CHECK_NEW == 1
    
    EIFEvectorized('INPUTS_EIFE_shapeBUB',BOUNDARY_CONDIDITONS,MAterialFile,DATALOC) ;
    
end

DATALOC1.FACE_TO_ANALIZE = 3 ;
DATALOC1.DOF_TO_ANALIZE = 1 ;
DATALOC1.LEGEND_LOC = 'EIFEM' ;
ExtractINFOplotNL_surfU(BOUNDARY_CONDIDITONS,DATALOC1) ;
%
% %%% OFFLINE STAGE
% OFFLINE_STEPS_LOCALaux(BOUNDARY_CONDIDITONS,DATAoffline)


