function T =    RotateStress2Dplanestrain(Q11,Q21) 

% Generated by 
% /home/joaquin/Desktop/CURRENT_TASKS/MATLAB_CODES/FE_HROM/LARGE_STRAINS/SYMBOLIC/ROTATE_STRESSES_2D.m

T = [   Q11^2,   Q21^2,     2*Q11*Q21
       Q21^2,   Q11^2,    -2*Q11*Q21
     -Q11*Q21, Q11*Q21, Q11^2 - Q21^2] ; 