function GenerateRVEsModes(NAME_MODES,COMPUTE_MODES_AGAIN,TOL_SINGULAR_VALUES_Hqr,...
    NAME_ROOT_FE,EXECUTABLE_FOLDER,DATAIN,NonRVEProjects,DATARUN,PROJECTS_TRAIN)

if nargin == 0
    load('tmp1.mat')
end

DATAIN = DefaultField(DATAIN,'RVES_SEL',[]) ;
FOLDER = [cd] ;
DATAIN.PLOT_RIGHT_SINGULAR_VECTORS = 15 ;% ------
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%NAME_PROJ_LOC = {'axial','torsion','pbend_y','pbend_z','sbend_y','sbend_z'} ;
PRESCRIBED_VALUE=[] ; NUMBER_OF_RVES = [] ; DATARUN.PRESCRIBED_DISPLACEMENTS = 0 ;

if isempty(PROJECTS_TRAIN)
    [NAMEPROJECTS] =     NameProjectsTraining2Drve(PRESCRIBED_VALUE,NUMBER_OF_RVES,NAME_ROOT_FE,DATARUN) ;
else
    NAMEPROJECTS = {} ;
end


if ~isempty(NAMEPROJECTS)
    [DATA_TRAINING,DATAIN ]= PropertiesProjectsMODES(DATAIN,NAMEPROJECTS,FOLDER,COMPUTE_MODES_AGAIN,TOL_SINGULAR_VALUES_Hqr) ;
    DATAIN.TIME_STEPS_TO_INCLUDE_TRAINING = cell(size(DATA_TRAINING))  ;
else
    %   MESH3D.RVES(irve).PROJECTS_TRAIN.RVES{iproj} =[10:30  ] ;
    %     MESH3D.RVES(irve).PROJECTS_TRAIN.TIME_STEPS{iproj} =[  ] ;
    %     MESH3D.RVES(irve).PROJECTS_TRAIN.TOLERANCE_SVD_RVES_DISP{iproj}= 1e-5 ; %
    %     MESH3D.RVES(irve).PROJECTS_TRAIN.TOLERANCE_SVD_RVES_REACT{iproj}= 1e-4; %
    %     MESH3D.RVES(irve).PROJECTS_TRAIN.TOLERANCE_SVD_RVES_STRESS{iproj}=  1e-4 ; %
    DATA_TRAINING = PROJECTS_TRAIN.NAMEWS ;
    DATAIN.NMODES_PROJECT_DISPLACEMENTS =  cell(size(DATA_TRAINING));
    DATAIN.NMODES_PROJECT_REACTIONS =    cell(size(DATA_TRAINING));;
    DATAIN.DOMAINS_TO_INCLUDE_TRAINING = PROJECTS_TRAIN.RVES;
    DATAIN.COMPUTE_MODES_AGAIN = COMPUTE_MODES_AGAIN ;
    DATAIN.TIME_STEPS_TO_INCLUDE_TRAINING = PROJECTS_TRAIN.TIME_STEPS ;
    DATAIN.TOLERANCE_SVD_RVES_DISP = PROJECTS_TRAIN.TOLERANCE_SVD_RVES_DISP ;
    DATAIN.TOLERANCE_SVD_RVES_REACT = PROJECTS_TRAIN.TOLERANCE_SVD_RVES_REACT ;
    DATAIN.TOLERANCE_SVD_RVES_STRESS = PROJECTS_TRAIN.TOLERANCE_SVD_RVES_STRESS ;
    
    PROJECTS_TRAIN = DefaultField(PROJECTS_TRAIN,'TOLERANCE_SVD_RVES_INTERNALF',[]);
    DATAIN.TOLERANCE_SVD_RVES_INTERNALF  =  PROJECTS_TRAIN.TOLERANCE_SVD_RVES_INTERNALF ;
    
end


% % NAME BINARY FILE (.mat) WHERE MODES  TO BE COMPUTED WILL BE STORED
if ~exist('MODES','dir')
    mkdir('MODES') ;
end
if isempty(NAME_MODES)
    NAMEFILE = mfilename ;
    
else
    NAMEFILE = NAME_MODES ;
end
DATAIN.NAME_WS_MODES = [cd,filesep,'MODES',filesep,'MODES_',NAMEFILE,'.mat'];

%DATAIN.NAMEWS = [cd,'/','MODES_',NAMEFILE,'.mat'];



%%% Information displacement face B in axial, shear.... tests (for beam modes)
% Disabled, 11-Jun-2019
%DATAIN.NameWs_displacementB_beams =    [ FOLDER,filesep,'DATAFE_TRAIN',filesep,NAME_ROOT_FE,'global.mat'] ; % [NAME_ROOT_FE,'global.mat'] ;

%%% END INPUT DATA %----------------------------------
cd(EXECUTABLE_FOLDER)
ExtractModesRVE(DATA_TRAINING,DATAIN) ;
cd(FOLDER)