function [NameFileRES,DATAIN ] = ...
    GIDprint_RVE_ROM(MESH2D,DATA_REFMESH,GeneralizedForces,DATAIN,DISP3D,a,DISP3D_lateral,...
    STRESS3D,STRESSDATA,FORCES_2_PRINT,MESH3D,FOLDER,DATARUN,DOFsKEEP,ndimINTF,DATAROM_glo)
% Post-process of GID results generated by reduced-order model
% Adapted from Plot3Dstructure.m ;
% and PrintGID1D_3Drepresentation.m, and GIDprint_BEAB_ROMslice.m
% JAHO, 4-May-2018/5-July-2018/25-July-2018
if nargin ==0
    load('tmp3.mat')
end
% 3D mesh DATA --> DATA_REFMESH
for ientity = 1:length(DATA_REFMESH)
    PROPS = MESH2D.PROP(ientity) ;
    switch PROPS.TYPE
        case 'RVE'
            INDEX = PROPS.INDEX_ENTITY ;
            %      NAME_SLICE = MESH3D.RVES(INDEX).DATA3D.NAME_SLICE
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %   MESH3D.RVES(INDEX).DATA3D = DATA_REFMESH{ientity} ;
            %  OLD_CONN = MESH3D.RVES(INDEX).DATA3D.CNb ;
            FFF = fieldnames( DATA_REFMESH{ientity} ) ;
            for ifield = 1:length(FFF)
                MESH3D.RVES(INDEX).DATA3D.(FFF{ifield}) = DATA_REFMESH{ientity}.(FFF{ifield}) ;
            end
            MESH3D.RVES(INDEX).DATA3D.CNb = MESH3D.RVES(INDEX).DATA3D.CONNECTb ;
            
            %  MESH3D.RVES(INDEX).DATA3D.NAME_SLICE = NAME_SLICE ;
            
        otherwise
            error('Option not implemented ')
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% lateral SURFACES
if  DATAIN.DISP3D_lateral == 1
    % Printing lateral surfaces
    for itype = 1:length(DATA_REFMESH)
        MESH2D.PROP(itype).LATERAL_SURFACES.PRINT_ALL =1; % Print all lateral surfaces
    end
else
    for itype = 1:length(DATA_REFMESH)
        MESH2D.PROP(itype).LATERAL_SURFACES.PRINT_ALL =0; % Print all lateral surfaces
    end
    
end

% WRITING MESH FILE
% -----------------------
DATAIN = DefaultField(DATAIN,'ONLY_SHOW_REDUCED_ELEMENTS',0) ; % Option, Dec-17,2019
if DATAIN.ONLY_SHOW_REDUCED_ELEMENTS ==1
    DATAIN.setReducedElements = DATAROM_glo{1}.HROMVAR.setElements ; 
else
    DATAIN.setReducedElements = [] ; 
    
end

% WRITING MESH FILE
% -----------------------
MESH3D_lateral.CONNECTb  = [] ; %DISP3D_lateral.CONNECTb ;
[NameFile_msh,NameFile_res,COOR,CN,NAME_INPUT_DATA,...
    TypeElement,MaterialType,NAMEMESH,DATAIN,DATAmeshR] = ...
    Construct3DstructureROMrve(MESH2D,MESH3D,DATAIN,MESH3D_lateral,FOLDER,DATA_REFMESH) ;

% Saving INFO for reconstruction of 3D geomeries with GID 
[FFF,nameSAVELOC,~ ]= fileparts(MESH2D.NAME); 
nameWSgeo  = [MESH2D.NAME,'.mat'] ; ; 
save(nameWSgeo,'DATAmeshR') ; 
 



IND_ELEM_MESHES = GidMesh2DFE_multi(NameFile_msh,COOR,CN,NAME_INPUT_DATA,MaterialType,TypeElement,NAMEMESH);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
nnode2D = size(MESH2D.COORall,1) ;
nnode3D = size(COOR,1)-nnode2D ;
NODES = {(1:nnode2D)', (1:nnode3D)'+nnode2D};
DATAIN = DefaultField(DATAIN,'PRINT_AVERAGE_STRESSES_ON_ELEMENTS',1) ;
if DATAIN.PRINT_AVERAGE_STRESSES_ON_ELEMENTS ==1
    posgp = cell(size(IND_ELEM_MESHES)) ;
else
    error('Option not implemented')
end

% -------------------
% WRITING .RES FILE
% -------------------
%STRESS3D = STRESS3D(:) ;
strainGLO = [] ;
React = [] ;
RESIDUAL = [] ;
% DISPLACEMENT
% 1D displacement
ndim = size(MESH3D.RVES(1).DATA3D.COOR,2) ;
DISP_2D = zeros(ndim,nnode2D) ;
DATAIN = DefaultField(DATAIN,'PLOT_2D_RESULTS',1) ;
if  DATAIN.PLOT_2D_RESULTS== 1 ;
    
    
    DISP_2D =  Determine2DfieldsRVE(a,MESH2D,ndim,MESH3D,DOFsKEEP,ndimINTF,DATAROM_glo,DATA_REFMESH) ;
    %     for idim = 1:ndim
    %         DISP_2D(idim,:) = a(idim:ndimGLO:end) ;
    %     end
end
DATAIN.ndimFE = ndim ; 
DATAIN.ndimINTF = ndimINTF ; 

% DISP3D = DISP3D' ;
DISP3D = [cell2mat(DISP3D')] ;
d = [DISP_2D(:); DISP3D(:)] ; % All displacements
%Forces and Moments (Diagrams)
DATA.GeneralizedForces = GeneralizedForces ;
%%
DATA.NAMEMESH = NAMEMESH;


DATAIN = DefaultField(DATAIN,'PlotUnified3Dmeshes',1) ;

if   DATAIN.PlotUnified3Dmeshes  == 1
    if ~isempty(STRESSDATA.VONMISES)
        STRESSDATA.VONMISES =  {cell2mat(STRESSDATA.VONMISES)} ;
    end
    if ~isempty(STRESS3D)
        STRESS3D = {cell2mat(STRESS3D')} ;
    end
    
end

DATAIN = DefaultField(DATAIN,'PRINT_MESH_ECM_POINTS_AS_POINTS',0) ; 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if  DATAIN.PRINT_MESH_ECM_POINTS_AS_POINTS == 0
[NameFileRES ]= GidPostProcess_multi_ROM(COOR,CN,TypeElement,d,strainGLO, STRESS3D, ...
    React,posgp,NameFile_res,MaterialType,NODES,RESIDUAL,DATAIN,DATA,STRESSDATA,IND_ELEM_MESHES,...
    FORCES_2_PRINT,DATA_REFMESH,DATARUN);
else
    disp('.RES GID FILE CANNOT BE PRINTED .... SET DATAIN.PRINT_MESH_ECM_POINTS_AS_POINTS=1 ')
    disp('Open instead the mesh file;')
    disp(NameFile_msh)
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

end


