filename = 'Cantileverbeam_Quadrilateral_Bilinear';
ptype = 'MACRO';
method = 'SIMPALL';
materialType = 'ISOTROPIC';
geomFunSettings.type = 'RectangleInclusion';
geomFunSettings.xSide = 0.8;
geomFunSettings.ySide = 0.4;
geomFunSettings.xCoorCenter = 1;
geomFunSettings.yCoorCenter = 0.5;
cost = {'compliance';'perimeter'};
weights = [1 0.1];
constraint = {'volumeConstraint'};
constraint_case = {'EQUALITY'};
target = 0.3;
optimizerUnconstrained = 'SLERP'; 
optimizer = 'AlternatingPrimalDual';
designVariable = 'LevelSet';
filterCostType = {'P1','PDE'};
filterConstraintType = {[]};

E1  = 1;
E0  = 1e-3;
nu1 = 1/3;
nu0 = 1/3;

plotting = false;
printing = false;
monitoring = false;
maxiter = 3;
