%% ========================================================================
%  POST-PROCESS - CASE C - NEW b-rho FORMULATION
%
%  Current formulation:
%
%       parameters = (b,rho)
%
%       b   in [1/3,3]
%       rho in [~0,0.998]
%
%       eta(b) =
%       kappa * (b - 1/b)/(bmax - 1/bmax)
%
%  Current dataset:
%
%       nB   = 73
%       nRho = 71
%
%  Network:
%
%       input transforms = identity, identity
%       hidden layers    = [150 200 300 200 150 50]
%       activation       = tanh
%       epochs           = 100000
%
%  Outputs:
%
%       HOM / NN surfaces
%       HOM-vs-NN errors
%       value curves
%       dC/db curves
%       dC/drho curves
%       b = 1 symmetry tests
%       anisotropy ratio
%       sensitivity competition Sb/Srho
%       volume fraction
%
%% ========================================================================

close all
clc


%% ========================================================================
% CONFIGURATION
%% ========================================================================

dataFile = ...
    'Homogenizationtwovariables28NEW.mat';

historyFile = ...
    'NNhistory_CaseC_brho_identity_tanh_100k.mat';

outFolder = ...
    'PostProcess_CaseC_73x71_Output';

if ~exist(outFolder,'dir')
    mkdir(outFolder);
end


%% ========================================================================
% LOAD DATA
%% ========================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf(' CASE C - b-rho POST-PROCESS\n');
fprintf('============================================================\n');

fprintf('Loading:\n%s\n\n',dataFile);

H = load(dataFile);

assert(isfield(H,'Chomog'), ...
    'Chomog is missing.');

assert(isfield(H,'paramB'), ...
    'paramB is missing.');

assert(isfield(H,'paramRho'), ...
    'paramRho is missing.');

assert(isfield(H,'volFrac'), ...
    'volFrac is missing.');

assert(isfield(H,'Interpolation'), ...
    'Interpolation is missing.');


Chomog        = H.Chomog;
paramB        = H.paramB(:)';
paramRho      = H.paramRho(:);
volFrac       = H.volFrac;
Interpolation = H.Interpolation;


nB   = numel(paramB);
nRho = numel(paramRho);

db   = mean(diff(paramB));
drho = mean(diff(paramRho));


fprintf('Grid = %d rho x %d b\n', ...
    nRho,nB);

fprintf('b    = [%.12f , %.12f]\n', ...
    paramB(1),paramB(end));

fprintf('rho  = [%.12f , %.12f]\n', ...
    paramRho(1),paramRho(end));

fprintf('db   = %.12e\n',db);
fprintf('drho = %.12e\n',drho);


[distB1,ibOne] = min(abs(paramB-1));

fprintf('Closest b to 1 = %.16f\n', ...
    paramB(ibOne));

fprintf('|b-1|          = %.3e\n', ...
    distB1);


[Bgrid,RHOgrid] = ...
    meshgrid(paramB,paramRho);


%% ========================================================================
% COMPONENT DEFINITIONS
%% ========================================================================

compNames = { ...
    'C1111', ...
    'C1122', ...
    'C1112', ...
    'C2222', ...
    'C2212', ...
    'C1212'};

compLabels = { ...
    '$C_{1111}$', ...
    '$C_{1122}$', ...
    '$C_{1112}$', ...
    '$C_{2222}$', ...
    '$C_{2212}$', ...
    '$C_{1212}$'};

compIds = { ...
    [1 1 1 1]
    [1 1 2 2]
    [1 1 1 2]
    [2 2 2 2]
    [2 2 1 2]
    [1 2 1 2]};

nComp = numel(compNames);


%% ========================================================================
% EXTRACT HOM SURFACES
%% ========================================================================

Yhom = zeros(nRho,nB,nComp);

for ic = 1:nComp

    id = compIds{ic};

    Yhom(:,:,ic) = squeeze( ...
        Chomog( ...
        id(1), ...
        id(2), ...
        id(3), ...
        id(4), ...
        :,:));

end


%% ========================================================================
% EVALUATE NN SURFACES
%% ========================================================================

fprintf('\nEvaluating NN surfaces...\n');

Ynn = zeros(nRho,nB,nComp);

bFlat   = Bgrid(:);
rhoFlat = RHOgrid(:);


for ic = 1:nComp

    id = compIds{ic};

    funNN = ...
        Interpolation.fun{ ...
        id(1), ...
        id(2), ...
        id(3), ...
        id(4)};

    values = ...
        funNN(bFlat,rhoFlat);

    Ynn(:,:,ic) = ...
        reshape(values,nRho,nB);

end

fprintf('NN surfaces evaluated.\n');


%% ========================================================================
% NN DERIVATIVES
%% ========================================================================

fprintf('Evaluating NN derivatives...\n');

dB_nn   = zeros(nRho,nB,nComp);
dRho_nn = zeros(nRho,nB,nComp);


for ic = 1:nComp

    id = compIds{ic};

    dfunNN = ...
        Interpolation.dfun{ ...
        id(1), ...
        id(2), ...
        id(3), ...
        id(4)};

    derivative = ...
        dfunNN(bFlat,rhoFlat);

    dB_nn(:,:,ic) = ...
        reshape( ...
        derivative{1}, ...
        nRho,nB);

    dRho_nn(:,:,ic) = ...
        reshape( ...
        derivative{2}, ...
        nRho,nB);

end

fprintf('NN derivatives evaluated.\n');


%% ========================================================================
% HOM DERIVATIVES - 5 POINT CENTRAL DIFFERENCE
%
%   f'(x_i) =
%
%   [f(i-2) - 8 f(i-1) + 8 f(i+1) - f(i+2)]
%   ------------------------------------------------
%                      12 h
%
%% ========================================================================

dB_hom   = nan(nRho,nB,nComp);
dRho_hom = nan(nRho,nB,nComp);


for ic = 1:nComp

    C = Yhom(:,:,ic);


    % --------------------------------------------------------------------
    % derivative with respect to b
    % --------------------------------------------------------------------

    dB_hom(:,3:end-2,ic) = ...
        ( ...
        C(:,1:end-4) ...
        - 8*C(:,2:end-3) ...
        + 8*C(:,4:end-1) ...
        - C(:,5:end) ...
        )/(12*db);


    % --------------------------------------------------------------------
    % derivative with respect to rho
    % --------------------------------------------------------------------

    dRho_hom(3:end-2,:,ic) = ...
        ( ...
        C(1:end-4,:) ...
        - 8*C(2:end-3,:) ...
        + 8*C(4:end-1,:) ...
        - C(5:end,:) ...
        )/(12*drho);

end


%% ========================================================================
% USEFUL DOMAIN MASK
%% ========================================================================

maskInterior = false(nRho,nB);

maskInterior(3:end-2,3:end-2) = true;


maskUseful = ...
    maskInterior & ...
    RHOgrid >= 0.10 & ...
    RHOgrid <= 0.90;


%% ========================================================================
% PRINT BASIC NN ERRORS
%% ========================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf(' NN ERROR SUMMARY\n');
fprintf('============================================================\n');

fprintf('%9s %14s %14s %14s\n', ...
    'Comp', ...
    'Value', ...
    'd/db', ...
    'd/drho');


for ic = 1:nComp

    H = Yhom(:,:,ic);
    N = Ynn(:,:,ic);

    Hb = dB_hom(:,:,ic);
    Nb = dB_nn(:,:,ic);

    Hr = dRho_hom(:,:,ic);
    Nr = dRho_nn(:,:,ic);


    eValue = ...
        norm(N(maskUseful)-H(maskUseful)) / ...
        max(norm(H(maskUseful)),eps);


    eB = ...
        norm(Nb(maskUseful)-Hb(maskUseful)) / ...
        max(norm(Hb(maskUseful)),eps);


    eR = ...
        norm(Nr(maskUseful)-Hr(maskUseful)) / ...
        max(norm(Hr(maskUseful)),eps);


    fprintf('%9s %14.6e %14.6e %14.6e\n', ...
        compNames{ic}, ...
        eValue,eB,eR);

end


%% ========================================================================
% 1 - HOM SURFACES
%% ========================================================================

for ic = 1:nComp

    fig = figure( ...
        'Color','w', ...
        'Position',[80 80 900 700]);

    surf( ...
        Bgrid, ...
        RHOgrid, ...
        Yhom(:,:,ic), ...
        'EdgeColor','none');

    xlabel('$b$', ...
        'Interpreter','latex');

    ylabel('$\rho$', ...
        'Interpreter','latex');

    zlabel(compLabels{ic}, ...
        'Interpreter','latex');

    title( ...
        ['HOM - ' compLabels{ic}], ...
        'Interpreter','latex');

    view(45,30);

    grid on
    box on
    colorbar

    exportgraphics( ...
        fig, ...
        fullfile( ...
        outFolder, ...
        ['HOM_Surface_' compNames{ic} '.png']), ...
        'Resolution',300);

    savefig( ...
        fig, ...
        fullfile( ...
        outFolder, ...
        ['HOM_Surface_' compNames{ic} '.fig']));

    close(fig)

end


%% ========================================================================
% 2 - NN SURFACES
%% ========================================================================

for ic = 1:nComp

    fig = figure( ...
        'Color','w', ...
        'Position',[80 80 900 700]);

    surf( ...
        Bgrid, ...
        RHOgrid, ...
        Ynn(:,:,ic), ...
        'EdgeColor','none');

    xlabel('$b$', ...
        'Interpreter','latex');

    ylabel('$\rho$', ...
        'Interpreter','latex');

    zlabel(compLabels{ic}, ...
        'Interpreter','latex');

    title( ...
        ['NN - ' compLabels{ic}], ...
        'Interpreter','latex');

    view(45,30);

    grid on
    box on
    colorbar

    exportgraphics( ...
        fig, ...
        fullfile( ...
        outFolder, ...
        ['NN_Surface_' compNames{ic} '.png']), ...
        'Resolution',300);

    savefig( ...
        fig, ...
        fullfile( ...
        outFolder, ...
        ['NN_Surface_' compNames{ic} '.fig']));

    close(fig)

end


%% ========================================================================
% 3 - HOM vs NN + ERROR MAPS
%% ========================================================================

for ic = 1:nComp

    Zhom = Yhom(:,:,ic);
    Znn  = Ynn(:,:,ic);

    errAbs = ...
        abs(Znn-Zhom);

    scale = ...
        max(abs(Zhom),[],'all');

    if scale < 1e-14
        scale = 1;
    end

    errGlobal = ...
        errAbs/scale;


    fig = figure( ...
        'Color','w', ...
        'Position',[50 50 1400 900]);


    t = tiledlayout( ...
        2,2, ...
        'Padding','compact', ...
        'TileSpacing','compact');


    % --------------------------------------------------------------------
    % HOM
    % --------------------------------------------------------------------

    nexttile

    surf( ...
        Bgrid, ...
        RHOgrid, ...
        Zhom, ...
        'EdgeColor','none');

    xlabel('$b$','Interpreter','latex');
    ylabel('$\rho$','Interpreter','latex');

    title('HOM');

    view(45,30);
    grid on
    box on
    colorbar


    % --------------------------------------------------------------------
    % NN
    % --------------------------------------------------------------------

    nexttile

    surf( ...
        Bgrid, ...
        RHOgrid, ...
        Znn, ...
        'EdgeColor','none');

    xlabel('$b$','Interpreter','latex');
    ylabel('$\rho$','Interpreter','latex');

    title('NN');

    view(45,30);
    grid on
    box on
    colorbar


    % --------------------------------------------------------------------
    % absolute error
    % --------------------------------------------------------------------

    nexttile

    imagesc( ...
        paramB, ...
        paramRho, ...
        errAbs);

    axis xy

    xlabel('$b$','Interpreter','latex');
    ylabel('$\rho$','Interpreter','latex');

    title('$|C^{NN}-C^{HOM}|$', ...
        'Interpreter','latex');

    colorbar


    % --------------------------------------------------------------------
    % normalized error
    % --------------------------------------------------------------------

    nexttile

    imagesc( ...
        paramB, ...
        paramRho, ...
        errGlobal);

    axis xy

    xlabel('$b$','Interpreter','latex');
    ylabel('$\rho$','Interpreter','latex');

    title( ...
        '$|C^{NN}-C^{HOM}|/\max |C^{HOM}|$', ...
        'Interpreter','latex');

    colorbar


    title( ...
        t, ...
        ['HOM vs NN - ' compLabels{ic}], ...
        'Interpreter','latex');


    exportgraphics( ...
        fig, ...
        fullfile( ...
        outFolder, ...
        ['HOM_vs_NN_' compNames{ic} '.png']), ...
        'Resolution',300);

    close(fig)

end


%% ========================================================================
% 4 - COMPONENT CURVES vs b
%
% Multiple fixed rho values
%% ========================================================================

rhoTargets = [ ...
    0.30 ...
    0.50 ...
    0.70 ...
    0.90];


for ic = 1:nComp

    fig = figure( ...
        'Color','w', ...
        'Position',[50 50 1300 900]);

    t = tiledlayout( ...
        2,2, ...
        'Padding','compact', ...
        'TileSpacing','compact');


    for kr = 1:numel(rhoTargets)

        [~,ir] = ...
            min(abs(paramRho-rhoTargets(kr)));

        rhoFix = ...
            paramRho(ir);


        nexttile

        plot( ...
            paramB, ...
            Yhom(ir,:,ic), ...
            'o-', ...
            'LineWidth',1.4, ...
            'MarkerSize',3);

        hold on


        bFine = ...
            linspace( ...
            min(paramB), ...
            max(paramB), ...
            500);


        id = compIds{ic};

        funNN = ...
            Interpolation.fun{ ...
            id(1), ...
            id(2), ...
            id(3), ...
            id(4)};


        yFine = ...
            funNN( ...
            bFine(:), ...
            rhoFix*ones(numel(bFine),1));


        plot( ...
            bFine, ...
            yFine, ...
            '--', ...
            'LineWidth',2);


        xline( ...
            1, ...
            ':', ...
            'b=1');


        xlabel('$b$', ...
            'Interpreter','latex');

        ylabel( ...
            compLabels{ic}, ...
            'Interpreter','latex');

        title( ...
            sprintf('$\\rho = %.4f$',rhoFix), ...
            'Interpreter','latex');

        legend( ...
            'HOM', ...
            'NN', ...
            'Location','best');

        grid on
        box on

    end


    title( ...
        t, ...
        [compLabels{ic} ' vs $b$: HOM vs NN'], ...
        'Interpreter','latex');


    exportgraphics( ...
        fig, ...
        fullfile( ...
        outFolder, ...
        ['Curves_' compNames{ic} '_vs_b.png']), ...
        'Resolution',300);

    close(fig)

end


%% ========================================================================
% 5 - dC/db vs b
%
% HOM = 5-point finite difference
% NN  = analytical network derivative
%% ========================================================================

bInterior = ...
    paramB(3:end-2);


for ic = 1:nComp

    fig = figure( ...
        'Color','w', ...
        'Position',[50 50 1300 900]);

    t = tiledlayout( ...
        2,2, ...
        'Padding','compact', ...
        'TileSpacing','compact');


    for kr = 1:numel(rhoTargets)

        [~,ir] = ...
            min(abs(paramRho-rhoTargets(kr)));

        rhoFix = ...
            paramRho(ir);


        nexttile


        yH = squeeze( ...
            dB_hom( ...
            ir, ...
            3:end-2, ...
            ic));


        yN = squeeze( ...
            dB_nn( ...
            ir, ...
            3:end-2, ...
            ic));


        plot( ...
            bInterior, ...
            yH, ...
            '-', ...
            'LineWidth',2);

        hold on


        plot( ...
            bInterior, ...
            yN, ...
            '--', ...
            'LineWidth',2);


        yline(0,':');


        xline( ...
            1, ...
            ':', ...
            'b=1');


        xlabel('$b$', ...
            'Interpreter','latex');

        ylabel( ...
            ['$\partial ' ...
            compLabels{ic}(2:end-1) ...
            '/\partial b$'], ...
            'Interpreter','latex');


        title( ...
            sprintf('$\\rho = %.4f$',rhoFix), ...
            'Interpreter','latex');


        legend( ...
            'HOM 5-point', ...
            'NN analytical', ...
            'Location','best');


        grid on
        box on

    end


    title( ...
        t, ...
        ['$\partial ' ...
        compLabels{ic}(2:end-1) ...
        '/\partial b$: HOM vs NN'], ...
        'Interpreter','latex');


    exportgraphics( ...
        fig, ...
        fullfile( ...
        outFolder, ...
        ['Derivative_d' compNames{ic} '_db.png']), ...
        'Resolution',300);

    close(fig)

end


%% ========================================================================
% 6 - dC/drho vs rho
%
% Fixed b values
%% ========================================================================

bTargets = [ ...
    1/3 ...
    1.0 ...
    5/3 ...
    3.0];

rhoInterior = ...
    paramRho(3:end-2);


for ic = 1:nComp

    fig = figure( ...
        'Color','w', ...
        'Position',[50 50 1300 900]);

    t = tiledlayout( ...
        2,2, ...
        'Padding','compact', ...
        'TileSpacing','compact');


    for kb = 1:numel(bTargets)

        [~,ib] = ...
            min(abs(paramB-bTargets(kb)));

        bFix = ...
            paramB(ib);


        nexttile


        yH = squeeze( ...
            dRho_hom( ...
            3:end-2, ...
            ib, ...
            ic));


        yN = squeeze( ...
            dRho_nn( ...
            3:end-2, ...
            ib, ...
            ic));


        plot( ...
            rhoInterior, ...
            yH, ...
            '-', ...
            'LineWidth',2);

        hold on


        plot( ...
            rhoInterior, ...
            yN, ...
            '--', ...
            'LineWidth',2);


        yline(0,':');


        xlabel('$\rho$', ...
            'Interpreter','latex');

        ylabel( ...
            ['$\partial ' ...
            compLabels{ic}(2:end-1) ...
            '/\partial \rho$'], ...
            'Interpreter','latex');


        title( ...
            sprintf('$b = %.4f$',bFix), ...
            'Interpreter','latex');


        legend( ...
            'HOM 5-point', ...
            'NN analytical', ...
            'Location','best');


        grid on
        box on

    end


    title( ...
        t, ...
        ['$\partial ' ...
        compLabels{ic}(2:end-1) ...
        '/\partial \rho$: HOM vs NN'], ...
        'Interpreter','latex');


    exportgraphics( ...
        fig, ...
        fullfile( ...
        outFolder, ...
        ['Derivative_d' compNames{ic} '_drho.png']), ...
        'Resolution',300);

    close(fig)

end


%% ========================================================================
% 7 - SPECIAL CENTRAL STATE b = 1
%
% Exact HOM theory:
%
%   C1111(1,rho) = C2222(1,rho)
%
%   C1111,b(1,rho) = -C2222,b(1,rho)
%
%   C1122,b(1,rho) = 0
%
%   C1212,b(1,rho) = 0
%
%% ========================================================================

fig = figure( ...
    'Color','w', ...
    'Position',[50 50 1400 900]);


t = tiledlayout( ...
    2,2, ...
    'Padding','compact', ...
    'TileSpacing','compact');


% ------------------------------------------------------------------------
% C11 vs C22 - HOM
% ------------------------------------------------------------------------

nexttile

plot( ...
    paramRho, ...
    Yhom(:,ibOne,1), ...
    '-', ...
    'LineWidth',2);

hold on

plot( ...
    paramRho, ...
    Yhom(:,ibOne,4), ...
    '--', ...
    'LineWidth',2);

xlabel('$\rho$', ...
    'Interpreter','latex');

ylabel('$C$', ...
    'Interpreter','latex');

title('HOM: $C_{1111}$ vs $C_{2222}$', ...
    'Interpreter','latex');

legend( ...
    '$C_{1111}$', ...
    '$C_{2222}$', ...
    'Interpreter','latex', ...
    'Location','best');

grid on
box on


% ------------------------------------------------------------------------
% C11 vs C22 - NN
% ------------------------------------------------------------------------

nexttile

plot( ...
    paramRho, ...
    Ynn(:,ibOne,1), ...
    '-', ...
    'LineWidth',2);

hold on

plot( ...
    paramRho, ...
    Ynn(:,ibOne,4), ...
    '--', ...
    'LineWidth',2);

xlabel('$\rho$', ...
    'Interpreter','latex');

ylabel('$C$', ...
    'Interpreter','latex');

title('NN: $C_{1111}$ vs $C_{2222}$', ...
    'Interpreter','latex');

legend( ...
    '$C_{1111}$', ...
    '$C_{2222}$', ...
    'Interpreter','latex', ...
    'Location','best');

grid on
box on


% ------------------------------------------------------------------------
% derivative symmetry
% ------------------------------------------------------------------------

nexttile

plot( ...
    paramRho, ...
    dB_hom(:,ibOne,1), ...
    '-', ...
    'LineWidth',2);

hold on

plot( ...
    paramRho, ...
    -dB_hom(:,ibOne,4), ...
    '--', ...
    'LineWidth',2);

plot( ...
    paramRho, ...
    dB_nn(:,ibOne,1), ...
    '-.', ...
    'LineWidth',1.8);

plot( ...
    paramRho, ...
    -dB_nn(:,ibOne,4), ...
    ':', ...
    'LineWidth',2);

xlabel('$\rho$', ...
    'Interpreter','latex');

ylabel('$\partial C/\partial b$', ...
    'Interpreter','latex');

title( ...
    '$C_{1111,b}$ vs $-C_{2222,b}$', ...
    'Interpreter','latex');

legend( ...
    'HOM $C_{1111,b}$', ...
    'HOM $-C_{2222,b}$', ...
    'NN $C_{1111,b}$', ...
    'NN $-C_{2222,b}$', ...
    'Interpreter','latex', ...
    'Location','best');

grid on
box on


% ------------------------------------------------------------------------
% invariant derivatives
% ------------------------------------------------------------------------

nexttile

plot( ...
    paramRho, ...
    dB_nn(:,ibOne,2), ...
    '-', ...
    'LineWidth',2);

hold on

plot( ...
    paramRho, ...
    dB_nn(:,ibOne,6), ...
    '--', ...
    'LineWidth',2);

yline(0,':');

xlabel('$\rho$', ...
    'Interpreter','latex');

ylabel('$\partial C/\partial b$', ...
    'Interpreter','latex');

title( ...
    'NN invariant components at $b=1$', ...
    'Interpreter','latex');

legend( ...
    '$C_{1122,b}$', ...
    '$C_{1212,b}$', ...
    'Interpreter','latex', ...
    'Location','best');

grid on
box on


title( ...
    t, ...
    'Central reciprocal state: $b=1$', ...
    'Interpreter','latex');


exportgraphics( ...
    fig, ...
    fullfile( ...
    outFolder, ...
    'Central_State_b1.png'), ...
    'Resolution',300);

close(fig)


%% ========================================================================
% 8 - DIRECTIONAL ANISOTROPY RATIO
%
%   R = C1111/C2222
%% ========================================================================

fig = figure( ...
    'Color','w', ...
    'Position',[50 50 1300 900]);


t = tiledlayout( ...
    2,2, ...
    'Padding','compact', ...
    'TileSpacing','compact');


for kr = 1:numel(rhoTargets)

    [~,ir] = ...
        min(abs(paramRho-rhoTargets(kr)));

    rhoFix = ...
        paramRho(ir);


    ratioHom = ...
        Yhom(ir,:,1) ./ ...
        Yhom(ir,:,4);


    ratioNN = ...
        Ynn(ir,:,1) ./ ...
        Ynn(ir,:,4);


    nexttile


    plot( ...
        paramB, ...
        ratioHom, ...
        '-', ...
        'LineWidth',2);

    hold on


    plot( ...
        paramB, ...
        ratioNN, ...
        '--', ...
        'LineWidth',2);


    yline(1,':');

    xline(1,':');


    xlabel('$b$', ...
        'Interpreter','latex');

    ylabel( ...
        '$C_{1111}/C_{2222}$', ...
        'Interpreter','latex');


    title( ...
        sprintf('$\\rho = %.4f$',rhoFix), ...
        'Interpreter','latex');


    legend( ...
        'HOM', ...
        'NN', ...
        'Location','best');


    grid on
    box on

end


title( ...
    t, ...
    'Directional anisotropy ratio', ...
    'Interpreter','latex');


exportgraphics( ...
    fig, ...
    fullfile( ...
    outFolder, ...
    'Anisotropy_Ratio_HOM_vs_NN.png'), ...
    'Resolution',300);

close(fig)


%% ========================================================================
% 9 - ANISOTROPY MEASURE
%
% A = log(C1111/C2222)
%% ========================================================================

AHom = ...
    log( ...
    Yhom(:,:,1) ./ ...
    Yhom(:,:,4));

ANN = ...
    log( ...
    Ynn(:,:,1) ./ ...
    Ynn(:,:,4));


fig = figure( ...
    'Color','w', ...
    'Position',[50 50 1200 550]);


t = tiledlayout( ...
    1,2, ...
    'Padding','compact', ...
    'TileSpacing','compact');


nexttile

imagesc( ...
    paramB, ...
    paramRho, ...
    AHom);

axis xy

xlabel('$b$', ...
    'Interpreter','latex');

ylabel('$\rho$', ...
    'Interpreter','latex');

title( ...
    'HOM: $\log(C_{1111}/C_{2222})$', ...
    'Interpreter','latex');

colorbar


nexttile

imagesc( ...
    paramB, ...
    paramRho, ...
    ANN);

axis xy

xlabel('$b$', ...
    'Interpreter','latex');

ylabel('$\rho$', ...
    'Interpreter','latex');

title( ...
    'NN: $\log(C_{1111}/C_{2222})$', ...
    'Interpreter','latex');

colorbar


title( ...
    t, ...
    'Directional anisotropy field', ...
    'Interpreter','latex');


exportgraphics( ...
    fig, ...
    fullfile( ...
    outFolder, ...
    'Anisotropy_LogRatio_Map.png'), ...
    'Resolution',300);

close(fig)


%% ========================================================================
% 10 - CONSTITUTIVE SENSITIVITY COMPETITION
%
% Same diagnostic used in validation:
%
%       Sb   = Delta_b   ||C_,b||
%       Srho = Delta_rho ||C_,rho||
%
% We use the four primary orthotropic components:
%
%       C1111
%       C1122
%       C2222
%       C1212
%
%% ========================================================================

id11 = 1;
id12 = 2;
id22 = 4;
id66 = 6;


normB_H = sqrt( ...
    dB_hom(:,:,id11).^2 + ...
    2*dB_hom(:,:,id12).^2 + ...
    dB_hom(:,:,id22).^2 + ...
    dB_hom(:,:,id66).^2);


normR_H = sqrt( ...
    dRho_hom(:,:,id11).^2 + ...
    2*dRho_hom(:,:,id12).^2 + ...
    dRho_hom(:,:,id22).^2 + ...
    dRho_hom(:,:,id66).^2);


normB_N = sqrt( ...
    dB_nn(:,:,id11).^2 + ...
    2*dB_nn(:,:,id12).^2 + ...
    dB_nn(:,:,id22).^2 + ...
    dB_nn(:,:,id66).^2);


normR_N = sqrt( ...
    dRho_nn(:,:,id11).^2 + ...
    2*dRho_nn(:,:,id12).^2 + ...
    dRho_nn(:,:,id22).^2 + ...
    dRho_nn(:,:,id66).^2);


deltaB = ...
    max(paramB)-min(paramB);

deltaRho = ...
    max(paramRho)-min(paramRho);


Sb_H = ...
    deltaB*normB_H;

Sr_H = ...
    deltaRho*normR_H;


Sb_N = ...
    deltaB*normB_N;

Sr_N = ...
    deltaRho*normR_N;


ratioSensitivityH = ...
    Sb_H ./ max(Sr_H,eps);

ratioSensitivityN = ...
    Sb_N ./ max(Sr_N,eps);


logRatioH = ...
    log10(ratioSensitivityH);

logRatioN = ...
    log10(ratioSensitivityN);


fig = figure( ...
    'Color','w', ...
    'Position',[50 50 1200 550]);


t = tiledlayout( ...
    1,2, ...
    'Padding','compact', ...
    'TileSpacing','compact');


nexttile

imagesc( ...
    paramB, ...
    paramRho, ...
    logRatioH);

axis xy

xlabel('$b$', ...
    'Interpreter','latex');

ylabel('$\rho$', ...
    'Interpreter','latex');

title( ...
    'HOM: $\log_{10}(S_b/S_\rho)$', ...
    'Interpreter','latex');

colorbar


nexttile

imagesc( ...
    paramB, ...
    paramRho, ...
    logRatioN);

axis xy

xlabel('$b$', ...
    'Interpreter','latex');

ylabel('$\rho$', ...
    'Interpreter','latex');

title( ...
    'NN: $\log_{10}(S_b/S_\rho)$', ...
    'Interpreter','latex');

colorbar


title( ...
    t, ...
    'Constitutive competition: $b$ versus $\rho$', ...
    'Interpreter','latex');


exportgraphics( ...
    fig, ...
    fullfile( ...
    outFolder, ...
    'Sensitivity_Competition_Sb_Srho.png'), ...
    'Resolution',300);

close(fig)


%% ========================================================================
% 11 - VOLUME FRACTION
%% ========================================================================

rhoMatrix = ...
    repmat(paramRho,1,nB);


fig = figure( ...
    'Color','w', ...
    'Position',[100 100 900 700]);


imagesc( ...
    paramB, ...
    paramRho, ...
    volFrac);

axis xy

xlabel('$b$', ...
    'Interpreter','latex');

ylabel('$\rho$', ...
    'Interpreter','latex');

title( ...
    'Computed physical volume fraction', ...
    'Interpreter','latex');

colorbar


exportgraphics( ...
    fig, ...
    fullfile( ...
    outFolder, ...
    'VolumeFraction_Map.png'), ...
    'Resolution',300);

close(fig)


%% ========================================================================
% VOLUME FRACTION ERROR
%% ========================================================================

volError = ...
    abs(volFrac-rhoMatrix);


fig = figure( ...
    'Color','w', ...
    'Position',[100 100 900 700]);


imagesc( ...
    paramB, ...
    paramRho, ...
    volError);

axis xy

xlabel('$b$', ...
    'Interpreter','latex');

ylabel('$\rho$', ...
    'Interpreter','latex');

title( ...
    '$|V_f-\rho|$', ...
    'Interpreter','latex');

colorbar


exportgraphics( ...
    fig, ...
    fullfile( ...
    outFolder, ...
    'VolumeFraction_Error.png'), ...
    'Resolution',300);

close(fig)


fprintf('\n');
fprintf('Maximum |Vf-rho| = %.6e\n', ...
    max(volError,[],'all'));

fprintf('RMS |Vf-rho|     = %.6e\n', ...
    sqrt(mean(volError(:).^2)));


%% ========================================================================
% 12 - TRAINING HISTORY
%% ========================================================================

if exist(historyFile,'file') == 2

    HH = load(historyFile);

    fprintf('\n');
    fprintf('History file found:\n');
    fprintf('%s\n',historyFile);

    fprintf('\nVariables inside history file:\n');

    names = fieldnames(HH);

    for i = 1:numel(names)
        fprintf('  %s\n',names{i});
    end


    history = [];

    if isfield(HH,'history')
        history = HH.history;
    end


    if isnumeric(history)

        fig = figure( ...
            'Color','w', ...
            'Position',[100 100 900 700]);

        semilogy( ...
            history(:), ...
            'LineWidth',1.5);

        xlabel('Epoch');
        ylabel('Loss');

        title( ...
            'NN training history');

        grid on
        box on


        exportgraphics( ...
            fig, ...
            fullfile( ...
            outFolder, ...
            'NN_Training_History.png'), ...
            'Resolution',300);

        close(fig)

    else

        fprintf( ...
            ['History exists but is not a simple numeric vector.\n' ...
             'It was therefore not plotted automatically.\n']);

    end

else

    fprintf('\n');
    fprintf('History file not found:\n');
    fprintf('%s\n',historyFile);

end


%% ========================================================================
% FINAL SUMMARY
%% ========================================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf(' POST-PROCESS FINISHED\n');
fprintf('============================================================\n');

fprintf('All figures saved in:\n');
fprintf('%s\n',outFolder);

fprintf('\n');

fprintf('Main new figures to inspect first:\n');

fprintf('  Central_State_b1.png\n');
fprintf('  Anisotropy_Ratio_HOM_vs_NN.png\n');
fprintf('  Sensitivity_Competition_Sb_Srho.png\n');
fprintf('  Derivative_dC1111_db.png\n');
fprintf('  Derivative_dC2222_db.png\n');
fprintf('  Derivative_dC1111_drho.png\n');
fprintf('  HOM_vs_NN_C1111.png\n');

fprintf('\n');