function Cinv = CrightINV_fromEgreenlST(E,nstrain,detC)
if nargin == 0
    E = [2
        3
        6   ] ;
    
    nstrain = 3 ;
    Emat = zeros(2,2) ;
    Emat(1,1) = E(1);
    Emat(1,2) = 0.5*E(3);
    Emat(2,1) = Emat(1,2) ;
    Emat(2,2)  = E(2) ;
    
    C = 2*Emat +  (eye(2)) ;
    
    detC = det(C) ;
    
    invC = inv(C)
    
end

SROWS = cell(1,nstrain) ;
for irows  =1:nstrain
    SROWS{irows} = irows:nstrain:size(E,1) ;
end
Cinv = zeros(size(E))  ;


if nstrain == 3
    % 2D
    % See CrightINV_fromEgreenlST_auxiliar.m
    %
    %
    % 2*E2 + 1
    % 2*E1 + 1
    %      -E3
    
    
    Cinv(SROWS{1}) = (2*E(SROWS{2}) + 1)./detC ;   % (2*E2 + 1)/detC
    Cinv(SROWS{2}) = (2*E(SROWS{1}) + 1)./detC ; % (2*E1 + 1)/detC
    Cinv(SROWS{3}) = (-E(SROWS{3}) )./detC ; % -E3/detC
    
else
    % Generated by CrightINV_fromEgreenlST_auxiliar.m
    
    Cinv(SROWS{1}) = (2.*E(SROWS{2}) + 2.*E(SROWS{3}) - E(SROWS{4}).^2 + 4.*E(SROWS{2}).*E(SROWS{3}) + 1)./detC;
    Cinv(SROWS{2}) = (2.*E(SROWS{1}) + 2.*E(SROWS{3}) - E(SROWS{5}).^2 + 4.*E(SROWS{1}).*E(SROWS{3}) + 1)./detC;
    Cinv(SROWS{3}) = (2.*E(SROWS{1}) + 2.*E(SROWS{2}) - E(SROWS{6}).^2 + 4.*E(SROWS{1}).*E(SROWS{2}) + 1)./detC;
    Cinv(SROWS{4}) = (E(SROWS{5}).*E(SROWS{6}) - 2.*E(SROWS{1}).*E(SROWS{4}) - E(SROWS{4}))./detC;
    Cinv(SROWS{5}) = (E(SROWS{4}).*E(SROWS{6}) - 2.*E(SROWS{2}).*E(SROWS{5}) - E(SROWS{5}))./detC;
    Cinv(SROWS{6}) = (E(SROWS{4}).*E(SROWS{5}) - 2.*E(SROWS{3}).*E(SROWS{6}) - E(SROWS{6}))./detC;
    
    
    
end