function Isym = Isym_LargeStrains(Cb,nstrain) 
%==========================================================================
% Isym_LargeStrains
%
% PURPOSE:
%   Construct the symmetric tensor product matrix `Isym` associated with
%   large strain constitutive models. This routine generates the terms
%   required to form quadratic invariants of the right Cauchy–Green
%   deformation tensor (or other symmetric strain-like measures) in
%   Voigt notation.
%
%   The resulting matrix `Isym` is used in the consistent linearization of
%   hyperelastic models, in particular for building the elasticity tensor
%   in Voigt form. The terms are expressed as quadratic combinations of the
%   components of the vector `Cb` (typically containing the components of
%   the deformation tensor in Voigt ordering).
%
%   The implementation covers two cases:
%     - nstrain = 3 : plane strain / 2D formulation (Voigt size = 3)
%     - nstrain = 6 : 3D formulation (Voigt size = 6)
%
%   The expressions are automatically generated by the auxiliary script
%   `Isym_LargeStrains_aux.m`, ensuring internal consistency of the
%   quadratic terms.
%
% INPUTS:
%   Cb       - (vector, size [nrows×1]) Values of the deformation tensor
%              components (in Voigt notation), stacked per quadrature point.
%   nstrain  - (integer) Number of strain components:
%                 3 → 2D/plane strain
%                 6 → 3D
%
% OUTPUTS:
%   Isym     - (matrix, size [nrows × nstrain]) Symmetric product matrix
%              containing quadratic terms of `Cb`. Each column corresponds
%              to a Voigt component of the second-order symmetric tensor.
%
% NOTES:
%   - The indexing of rows is handled through `SROWS`, which partitions the
%     rows of `Cb` corresponding to each Voigt component.
%   - For each case (nstrain = 3 or 6), the quadratic terms are explicitly
%     assembled to ensure symmetry of the tangent operator.
%   - Cross-terms are symmetrized (with factors 1/2) whenever needed.
%   - If `nstrain` is different from 3 or 6, the function throws an error.
%
% EXAMPLE USAGE:
%   % Suppose Cb contains the Voigt components of C for each Gauss point
%   Isym = Isym_LargeStrains(Cb,6);
%
%   % The resulting Isym can be contracted with material parameters
%   % to construct the consistent tangent stiffness tensor.
%   Comments generated automatically by ChatGPT-5, 3-Oct-2025
%--------------------------------------------------------------------------


if nargin == 0
    load('tmp.mat')
end

Isym = zeros(size(Cb,1),nstrain) ;


SROWS = cell(1,nstrain) ;
for irows  =1:nstrain
    SROWS{irows} = irows:nstrain:size(Cb,1) ;
end

if nstrain == 3
    % Generated automatically by
    %/home/joaquin/Desktop/CURRENT_TASKS/MATLAB_CODES/FE_HROM/LARGE_STRAINS/CONSTITUTIVE_MODELS/Isym_LargeStrains_aux.m
    Isym(SROWS{1},1) = Cb(SROWS{1}).^2;
    Isym(SROWS{1},2) = Cb(SROWS{3}).^2;
    Isym(SROWS{1},3) = Cb(SROWS{1}).*Cb(SROWS{3});
    Isym(SROWS{2},1) = Isym(SROWS{1},2);
    Isym(SROWS{2},2) = Cb(SROWS{2}).^2;
    Isym(SROWS{2},3) = Cb(SROWS{2}).*Cb(SROWS{3});
    Isym(SROWS{3},1) = Isym(SROWS{1},3);
    Isym(SROWS{3},2) = Isym(SROWS{2},3);
    Isym(SROWS{3},3) = Cb(SROWS{3}).^2./2 + (Cb(SROWS{1}).*Cb(SROWS{2}))./2;
    
elseif nstrain == 6
    % Generated automatically by
    %/home/joaquin/Desktop/CURRENT_TASKS/MATLAB_CODES/FE_HROM/LARGE_STRAINS/CONSTITUTIVE_MODELS/Isym_LargeStrains_aux.m
    
    Isym(SROWS{1},1) = Cb(SROWS{1}).^2;
    Isym(SROWS{1},2) = Cb(SROWS{6}).^2;
    Isym(SROWS{1},3) = Cb(SROWS{5}).^2;
    Isym(SROWS{1},4) = Cb(SROWS{5}).*Cb(SROWS{6});
    Isym(SROWS{1},5) = Cb(SROWS{1}).*Cb(SROWS{5});
    Isym(SROWS{1},6) = Cb(SROWS{1}).*Cb(SROWS{6});
    Isym(SROWS{2},1) = Isym(SROWS{1},2);
    Isym(SROWS{2},2) = Cb(SROWS{2}).^2;
    Isym(SROWS{2},3) = Cb(SROWS{4}).^2;
    Isym(SROWS{2},4) = Cb(SROWS{2}).*Cb(SROWS{4});
    Isym(SROWS{2},5) = Cb(SROWS{4}).*Cb(SROWS{6});
    Isym(SROWS{2},6) = Cb(SROWS{2}).*Cb(SROWS{6});
    Isym(SROWS{3},1) = Isym(SROWS{1},3);
    Isym(SROWS{3},2) = Isym(SROWS{2},3);
    Isym(SROWS{3},3) = Cb(SROWS{3}).^2;
    Isym(SROWS{3},4) = Cb(SROWS{3}).*Cb(SROWS{4});
    Isym(SROWS{3},5) = Cb(SROWS{3}).*Cb(SROWS{5});
    Isym(SROWS{3},6) = Cb(SROWS{4}).*Cb(SROWS{5});
    Isym(SROWS{4},1) = Isym(SROWS{1},4);
    Isym(SROWS{4},2) = Isym(SROWS{2},4);
    Isym(SROWS{4},3) = Isym(SROWS{3},4);
    Isym(SROWS{4},4) = Cb(SROWS{4}).^2./2 + (Cb(SROWS{2}).*Cb(SROWS{3}))./2;
    Isym(SROWS{4},5) = (Cb(SROWS{3}).*Cb(SROWS{6}))./2 + (Cb(SROWS{4}).*Cb(SROWS{5}))./2;
    Isym(SROWS{4},6) = (Cb(SROWS{2}).*Cb(SROWS{5}))./2 + (Cb(SROWS{4}).*Cb(SROWS{6}))./2;
    Isym(SROWS{5},1) = Isym(SROWS{1},5);
    Isym(SROWS{5},2) = Isym(SROWS{2},5);
    Isym(SROWS{5},3) = Isym(SROWS{3},5);
    Isym(SROWS{5},4) = Isym(SROWS{4},5);
    Isym(SROWS{5},5) = Cb(SROWS{5}).^2./2 + (Cb(SROWS{1}).*Cb(SROWS{3}))./2;
    Isym(SROWS{5},6) = (Cb(SROWS{1}).*Cb(SROWS{4}))./2 + (Cb(SROWS{5}).*Cb(SROWS{6}))./2;
    Isym(SROWS{6},1) = Isym(SROWS{1},6);
    Isym(SROWS{6},2) = Isym(SROWS{2},6);
    Isym(SROWS{6},3) = Isym(SROWS{3},6);
    Isym(SROWS{6},4) = Isym(SROWS{4},6);
    Isym(SROWS{6},5) = Isym(SROWS{5},6);
    Isym(SROWS{6},6) = Cb(SROWS{6}).^2./2 + (Cb(SROWS{1}).*Cb(SROWS{2}))./2;
    
    
    
else
    error('Option not implemented')
end
