function [qL_extended,qLATENT_LOC] = EncoderDamageModel_snap(BasisU_master,GmatN,SNAP_cluster,DOFl,idimLAT,DATA_evaluateTAU_and_DER)
% EncoderDamageModel_snap
% -------------------------------------------------------------------------
% PURPOSE
%   Compute the *latent coordinates* (qLIN, qNON) and their corresponding
%   *extended decoder coordinates* τ(q) for a given set of displacement
%   snapshots within a *univariate damage* manifold formulation.
%
%   This function acts as the **encoder** counterpart of tauFUN_1paramDAMAGE:
%   it projects the snapshots onto the reduced (linear + nonlinear) master
%   basis, normalizes them, and evaluates τ(q) using the spline-based decoder
%   stored in DATA_evaluateTAU_and_DER.
%
% INPUTS
%   BasisU_master  : [nDOF×n_master] reduced master basis used for encoding.
%                    Typically contains [Φ_lin, Φ_non,mst].
%   GmatN          : [nDOF×nDOF] symmetric positive-definite matrix defining
%                    the inner product (e.g., K_ll or M_geo,ll).
%   SNAP_cluster   : Struct containing snapshot SVD components:
%                      .DISP.U, .DISP.S, .DISP.V  (SVD of displacement data).
%   DOFl           : Indices of free/unconstrained DOFs.
%   idimLAT        : Integer index of the latent coordinate to extract from
%                    the extended τ(q) vector (e.g., 1 → qLIN, 2 → qNON).
%   DATA_evaluateTAU_and_DER :
%                    Struct containing the spline-based decoder info and the
%                    function handle nameFunctionEvaluate (usually
%                    'tauFUN_1paramDAMAGE'), used to compute τ(q).
%
% OUTPUTS
%   qL_extended    : [n_modes×n_snap] extended latent vector τ(qL), including
%                    [qLIN ; qLIN*qNON ; qLIN*g(qNON)] as defined in theory.
%   qLATENT_LOC    : [1×n_snap] selected component from τ(qL), corresponding
%                    to idimLAT (useful for plotting or parameter-space maps).
%
% METHOD
%   1) Project the displacement snapshots (U,S,V) onto the reduced master
%      basis using the weighted inner product G:
%         coeffs = Φ_masterᵀ G (U*S*Vᵀ).
%   2) Extract qLIN and qNON as the first two modal coefficients.
%   3) Normalize qNON by qLIN wherever |qLIN| > TOL⋅max|qLIN| to preserve
%      the factorized form τ(q) = qLIN*[1; qNON; g(qNON)].
%   4) Assemble qL = [qLIN; qNON].
%   5) Evaluate the nonlinear decoder τ(qL) using the provided spline data:
%         qL_extended = feval(nameFunctionEvaluate, qL, DATA_evaluateTAU_and_DER).
%   6) Extract the requested latent dimension:
%         qLATENT_LOC = qL_extended(idimLAT,:).
%
% ASSUMPTIONS
%   • The reduced basis BasisU_master is G-orthonormal.
%   • The first two reduced coordinates correspond to the linear and
%     nonlinear master latent variables (qLIN, qNON).
%   • DATA_evaluateTAU_and_DER was generated by Bsplines_EP_1stmodeDMG.
%
% APPLICATION
%   Used during postprocessing or reduced simulation to project snapshots
%   into the manifold latent space, enabling comparison or interpolation in
%   (qLIN, qNON) coordinates.
%
% VERSION / AUTHOR
%   24-Oct-2025 — J.A. Hernández (HGs, Pedralbes, Barcelona). Encoder counterpart of the
%   τ-decoder for the univariate damage manifold with K_ll metric.
% Comments by ChatGPT 5
% -------------------------------------------------------------------------

if nargin == 0
    load('tmp1.mat')
end
coeffsMasterModes = BasisU_master'*(GmatN*SNAP_cluster.DISP.U(DOFl,:)) ;  % SVD, U,S,V
coeffsMasterModes =bsxfun(@times,coeffsMasterModes',SNAP_cluster.DISP.S)' ;
coeffsMasterModes  = coeffsMasterModes*SNAP_cluster.DISP.V' ;
qLIN = coeffsMasterModes(1,:) ; 
qNON = coeffsMasterModes(2,:) ;

max_qLIN = max(abs(qLIN)) ; 
TOL = 1e-10 ; 
IndicesNotCloseToZero = find(abs(qLIN) > TOL*max_qLIN ) ; 
qNON(IndicesNotCloseToZero) = qNON(IndicesNotCloseToZero)./qLIN(IndicesNotCloseToZero) ; 

qL = [qLIN; qNON] ;
%   qL_extended = tauNON(qL) ;
[qL_extended] = feval(DATA_evaluateTAU_and_DER.nameFunctionEvaluate,qL,DATA_evaluateTAU_and_DER) ;
qLATENT_LOC = qL_extended(idimLAT,:) ;