function v = spval_cubic_univar(sp, x)
%SPVAL_CUBIC_UNIVAR Fast evaluation of univariate cubic B-form spline
%   v = spval_cubic_univar(sp, x)
%
%   sp : struct with fields 'knots', 'coefs', 'number', 'order', 'dim'
%        (univariate, scalar-valued, B-form, cubic: order = 4) 
%   x  : vector or array of evaluation points
%
%   v : same shape as x
% JAHO, 11th August 2025, generated by ChatGPT

% unpack spline
t = sp.knots;
a = sp.coefs; % row vector for scalar-valued case
n = sp.number;
k = sp.order; % should be 4
d = sp.dim;   % should be 1

% flatten input
[mx, nx] = size(x);
lx = mx * nx;
xs = reshape(x, 1, lx);

% augment knots if needed
index = find(diff(t) > 0);
addl = k - index(1);
addr = index(end) - n;
if addl > 0 || addr > 0
    npk = n + k;
    t = t([ones(1,addl), 1:npk, npk(ones(1,addr))]);
    a = [zeros(d,addl), a, zeros(d,addr)];
    n = n + addl + addr;
end

% knot interval lookup (right-continuous)
[~, idx] = histc(xs, [-inf, t(k+1:n), inf]);
NaNx = idx == 0;
idx = min(idx + (k - 1), n);
if any(NaNx), idx(NaNx) = k; end

% initialize for de Boor
didx = reshape(repmat(idx, d, 1), d*lx, 1);
tx = reshape(t(repmat(2-k:k-1, d*lx, 1) + repmat(didx, 1, 2*(k-1))), ...
             d*lx, 2*(k-1));
tx = tx - repmat(reshape(repmat(xs, d, 1), d*lx, 1), 1, 2*(k-1));

didx = reshape(repmat(d*idx, d, 1) + repmat((1-d:0).', 1, lx), d*lx, 1);
b = repmat(d*(1-k):d:0, d*lx, 1) + repmat(didx, 1, k);
a = a(:);
b(:) = a(b);

% de Boor recursion (k=4 → 3 iterations)
for r = 1:k-1
    for i = 1:k-r
        b(:, i) = (tx(:, i+k-1).*b(:, i) - tx(:, i+r-1).*b(:, i+1)) ./ ...
                  (tx(:, i+k-1) - tx(:, i+r-1));
    end
end

v = reshape(b(:,1), d*mx, nx);

% zero outside domain
outIdx = (x < t(1)) | (x > t(n+k));
if any(outIdx)
    v(outIdx) = 0;
end
end
