FemTestsSuite;
MicroShapeTestsSuite;
DiffReactTestsSuite;
UnfittedIntegrationTestsSuite;
VectorizedTriangulationTestsSuite;
close all;
TopOptTestsSuite;
ReadingFilesTestsSuite;
PlottingTestsSuite;
close all;
HomogenizationTestsSuite;
ImageProcessingTestsSuite;
%PostProcTestsSuite; S'ha de fer des de 0 i pensar en com (ara ignore it)
ProjectorsTestsSuite;
RemeshingTestsSuite;
DehomogenizationTestsSuite;
close all;
AcademicTestsSuite;
close all;
BoundaryCondTestsSuite;
GeomFunTestsSuite;
close all;