FemTestsSuite;
MicroShapeTestsSuite;
DiffReactTestsSuite;
UnfittedIntegrationTestsSuite;
VectorizedTriangulationTestsSuite;
close all;
TopOptTestsSuite;
ReadingFilesTestsSuite;
PlottingTestsSuite;
close all;
HomogenizationTestsSuite;
ImageProcessingTestsSuite;
PostProcTestsSuite;
ProjectorsTestsSuite;
RemeshingTestsSuite;
DehomogenizationTestsSuite;
close all;
AcademicTestsSuite;
close all;
BoundaryCondTestsSuite;
GeomFunTestsSuite;
close all;