FemTestsSuite;
UnfittedIntegrationTestsSuite;
VectorizedTriangulationTestsSuite;
close all;
TopOptTestsSuite;
ReadingFilesTestsSuite;
PlottingTestsSuite;
close all;
HomogenizationTestsSuite;
ImageProcessingTestsSuite;
