clc
clear all
%  /home/joaquin/Desktop/CURRENT_TASKS/MATLAB_CODES/TESTING_PROBLEMS_FEHROM/107_EIFEM_plast3D/03_PLATE_Q8.mlx
% TRAINING OF A Q8 EIF ELEMENT, TAILORED TO plate behavior
% -------------------------------------------------------

if ~exist('Quadratic3N')
    addpath(genpath('FE_HROM'))  ; %
end
INPUT_PROBLEMS ='DEF_Q8_wing' ;  % These are where the inputs for the basic training are defined
LABEL_DOMAIN = [1]; % LABEL IDENTIFYING THE SURFACE/VOLUME WE WISH TO STUDY (seldom used, I should remove it)
LABELS_FACES =   [7,8] ;   % LABELS IDENTIFYING THE BOUNDARY OF SUCH A DOMAIN, in the PRE-GID FILE ...Again, seldom used
%CORNERS_DEFINING_MACRO_ELEMENT_AS_INTERSECTIONS_ENTITIES = {[1,2],[2,3],[3,4],[4,1]} ;
NameWS_EIFE_oper_base  = [cd,filesep,'EIFE_LIBRARY',filesep,INPUT_PROBLEMS] ;  % Binary file where to store the  resulting
% Empirical Interscale FE %


DATAlauch.TRAINING =1;
DATAlauch.OFFLINE_modes_points =1;
DATAlauch.ONLINE_OPERATORS=1;


%%%%
DATAoffline.CECM_ONLY_FOR_NONLINEAR_STRESSES = 1;  % CUBATURE RULE SPECIFIC TO NONLINEAR TESTS
DATAoffline.TOLSVD_complementary_modes = 1e-3 ; % displacements
    DATAoffline.TOLSVD_INVARIANT_BASIC_MODES = 1e-5 ;
DATAoffline.TOL_cosine_ANGLES_WORK_DONE_INTERFACES = 1e-2 ; 


%  DATAoffline.THRESHOLD_RATIO_CONSECUTIVE_SINGLE_VALUES_INVARIANT_DEF_MODES = 10 ;   % Determine invariant modes
% DATAoffline.TOLSVD_INVARIANT_BASIC_MODES = 0 ; 

 % ----------------------------------------------------------
 DATAoffline.TOLSVD_complementary_modes_stresses =5e-1;
DATAoffline.errorFINT  =5e-1;



DATAoffline.errorMASSmatrixDECM = 1e-3;
%  DATAoffline.NPOINTS_ONE_DIRECTION_inverse_mapping  =10 ; % DefaultField(DATAoffline,'NPOINTS_ONE_DIRECTION_inverse_mapping',10) ;

DATAoffline.UseDECMpoints.INTERNAL_FORCES =1;
DATAoffline.UseDECMpoints.MASS_MATRIX =1;
%DATAoffline.NumberOfCECMpoints.MASS_MATRIX = []  ;
%DATAoffline.NumberOfCECMpoints.INTERNAL_FORCES = 20 ;
DATAoffline.LOAD_FROM_MEMORY_ECM_POINTS_INTERNAL_FORCES = 0;
DATAoffline.LOAD_FROM_MEMORY_ECM_POINTS_MASS_MATRIX = 0;

% Generated by 04_GeneralTheory/TensUnif_x.m
% Generated by 04_GeneralTheory/TensUnif_y.m

DATAoffline.AdditionalTests = {} ; % {[cd,'/SNAPSHOTS/BC_purebend_Lf_param_1/']} ;  {[cd,'/SNAPSHOTS/BC_purebend_LUf_param_1/']} ;



DATAoffline.StressModesComputation_viaCOEFFICIENTS_SVD_DEFORMATION = 0;


%DATAoffline.NUMBER_OF_DEFORMATIONAL_MODES = 9 ;
DATAoffline.CHECK_ACCURACY_PROJECTED_STRESSES =1;
DATAoffline.CHECK_ACCURACY_PROJECTED_STRESSES_AFTER_BUBBLE_MODES =0;


%DATAoffline.MAXIMUM_ANGLE_DEF_REACT_FOR_STRAIN_MODES = 89 ; % Degrees


%DATAoffline.TOLSVD_complementary_modes_stresses = 1e-3 ;
%DATAoffline.BASIS_STRESSES_FROM_PROJECTED_DISPLACEMENTS = 1;


DATAoffline.CECM_SECOND_STAGE_ITERATIONS = 20;
%

%
%
% for  itrain = 1:length(LABEL_DOMAIN)


%DATAoffline.LABEL_DOMAIN = LABEL_DOMAIN  ;
DATAoffline.LABEL_AUXDOMAINS = [] ;  %
DATAoffline.LABELS_FACES = LABELS_FACES ;

DATAoffline.CORNERS_DEFINING_MACRO_ELEMENT_AS_INTERSECTIONS_ENTITIES = [] ; 
 %   CORNERS_DEFINING_MACRO_ELEMENT_AS_INTERSECTIONS_ENTITIES  ;

NameWS_EIFE_oper = [NameWS_EIFE_oper_base,'_',num2str(1),'.mat'] ;
%DATAoffline.MESH_QUADRATIC_PARENT_DOMAIN = [cd,'/GIDPRE/',MESH_QUADRATIC_PARENT_DOMAIN ] ;
%%%%%%
Train1dom_BUBcomp(DATAlauch,INPUT_PROBLEMS,NameWS_EIFE_oper,DATAoffline)  ;

% end