function  IND_ELEM_MESHES = GidMesh2DFE_multi(NameFile,COOR,CONNECT_glo,NAMEPROJ,MaterialType,TypeElement,NAMEMESH)
% ---------------------------------------------------------------------------------------------------
% FUNCTION: GidMesh2DFE_multi
% ---------------------------------------------------------------------------------------------------
% PURPOSE:
%   This function generates a GiD-compatible `.msh` mesh file for 2D (or 3D) finite element meshes.
%   It supports multi-region meshes, with different element types, materials, and mesh names.
%   Additionally, it returns indices of elements corresponding to each submesh.
%
% USAGE:
%   IND_ELEM_MESHES = GidMesh2DFE_multi(NameFile, COOR, CONNECT_glo, NAMEPROJ, ...
%                                       MaterialType, TypeElement, NAMEMESH)
%
% INPUTS:
%   - NameFile     : String with the name (and path) of the output `.msh` file.
%   - COOR         : [nnode x ndim] array of nodal coordinates.
%   - CONNECT_glo  : Cell array of element connectivities for each mesh region.
%   - NAMEPROJ     : String name of the project or example (used in the file header).
%   - MaterialType : Cell array with material IDs for each element in each region.
%   - TypeElement  : Cell array with GiD element types (e.g., 'Triangle', 'Quadrilateral').
%   - NAMEMESH     : Cell array with mesh names for each region (used in the MESH block in GiD).
%
% OUTPUT:
%   - IND_ELEM_MESHES: Cell array. Each entry contains the global indices of the elements 
%                      associated with the corresponding submesh.
%
% FUNCTIONALITY:
%   - Writes GiD-compliant mesh headers, coordinates, elements, and material numbers.
%   - Handles multiple submeshes and ensures that coordinates are written only once.
%   - Assigns unique global element numbering across all mesh parts.
%
% EXAMPLE:
%   Used for writing simulation meshes to GiD for visualization/postprocessing.
%   Typically called prior to writing `.res` results files.
%
% AUTHOR:
%   Joaquín A. Hernández, UPC – CIMNE
%   Date: 09-Dec-2020 (last update)
%   Comments generated by ChatGPT-4, on 12-May-2025
% DEPENDENCIES:
%   - None
%   - Requires proper formatting of mesh data structures (COOR, CONNECT, etc.)
%
% ---------------------------------------------------------------------------------------------------

if nargin == 0
    load('tmp1.mat')
end

%%% INPUTS %%%%%%
numer_nodesTOT = 1:size(COOR,1) ;


fid = fopen(NameFile,'wt');
fprintf(fid,' # ================================================== \n',[]);
fprintf(fid,[' # \n'],[]);
fprintf(fid,' # POSTPROCESSING WITH GID - MESH FILE \n',[]);
fprintf(fid,[' # EXAMPLE NAME: ' NAMEPROJ ' \n'],[]);
fprintf(fid,' # ================================================== \n',[]);
iacumELEM = 0 ; 
IND_ELEM_MESHES ={} ;
for imesh = 1:length(CONNECT_glo)
    
    elem_type = TypeElement{imesh};
    CONNECT= CONNECT_glo{imesh};
    NNode=size(CONNECT,2);
    ndime = size(COOR,2) ;
    nnod = size(COOR,1) ;
    npe =  size(CONNECT,2) ;
    nElem = size(CONNECT,1) ;
    NAMEMESH_loc = NAMEMESH{imesh} ;
    MaterialType_loc = MaterialType{imesh} ;
    IND_ELEM_MESHES{imesh} = [iacumELEM+1:iacumELEM+nElem] ; 
    % 1.- Header with 6 free lines
    
    
    fprintf(fid,[' MESH "' NAMEMESH_loc '" dimension ' num2str(ndime) ' Elemtype ' elem_type ...
        ' Nnode ' num2str(NNode) '\n'],[]);
    fprintf(fid,' Coordinates \n',[]);
    if imesh ==1
        fprintf(fid,' # node number   coordinate_x  coordinate_y  coordinate_z \n',[]);
        
        % 4.- Coordinates
        format_xnod = [];
        for k=1:ndime,
            format_xnod = [format_xnod, '%15.5e'];
        end
        format_xnod=[' %10i ' format_xnod, '\n'];
        fprintf(fid,format_xnod,[numer_nodesTOT',COOR(:,1:ndime) ]');
    end
    fprintf(fid,' end coordinates \n',[]);
    
    fprintf(fid,' Elements \n',[]);
    
    format_title = ' # element ';
    for k=1:npe,
        format_title=[format_title, ' node_' num2str(k)];
    end
    format_title=[format_title, ' material number \n'];
    
    fprintf(fid,format_title,[]);
    
    format_icone = [];
    for k=1:npe,
        format_icone=[format_icone, '%10i'];
    end
    format_icone=['%10i ' format_icone, '     %10i ' '\n'];
    
    fprintf(fid,format_icone,[((1:nElem)+iacumELEM)',CONNECT, MaterialType_loc]');
    
    fprintf(fid,' end elements \n',[]);
    iacumELEM = iacumELEM + nElem ; 
end

fclose(fid);