fileName = 'bridgeExample_200x10_case2';
s.testName = [fileName,'.m'];
s.x1       = 10;
s.y1       = 2;
s.N        = 200;
s.M        = 10;
s.P        = -1;
s.DoF      = 2;
s.problemCase = 'bridge';
FEMWriter = FEMInputWriter(s);
FEMWriter.createTest();