function [xINInew,XYgrid,INDEXperm,MPOINTS] = ArrangePointsCartesianFromFEmesh(xINI) 
if nargin == 0
    load('tmp1.mat')
end
% Given an unordered set of points xINI (mpoints x ndim),
% ArrangePointsCartesianFromFEmesh returns
% 1) The grid vectors XYgrid{1}, XYgrid{2},..XYgrid{ndim}  (ndim = 2,3)
% 2) xINInew: The concatenation of all the points of the grid as generated by meshgrid 
% 3) The permutation indexes such that xINInew = xINI(INDEXperm,:)
% 4) MPOINTS :The number of points in each direction
% JAHO, 28-Nov-2021
% ----------------------------------------------------------------------------------------

ndim = size(xINI,2) ;

if ndim == 2 
    [xINInew,XYgrid,INDEXperm,MPOINTS] = ArrangePointsCartesianFromFEmesh2D(xINI);
end

