function [NameFileRES ]= GIDprint_BEAM_ROM_JOINTslice(MESH1D,DATA_REFMESH,GeneralizedForces,DATAIN,DISP3D,a,DISP3D_lateral,...
    STRESS3D,STRESSDATA,FORCES_2_PRINT,MESH3D,FOLDER,DATARUN,REACTIONS3D,DATAROM_glo)
% Post-process of GID results generated by reduced-order model
% Adapted from Plot3Dstructure.m ;
% and PrintGID1D_3Drepresentation.m
% JAHO, 4-May-2018/5-July-2018
if nargin ==0
    load('tmp0.mat')
end
% 3D mesh DATA --> DATA_REFMESH
for ientity = 1:length(DATA_REFMESH)
    PROPS = MESH1D.PROP(ientity) ;
    switch PROPS.TYPE
        case 'BEAM'
            INDEX = PROPS.INDEX_ENTITY ;
            %      NAME_SLICE = MESH3D.SLICES(INDEX).DATA3D.NAME_SLICE
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %   MESH3D.SLICES(INDEX).DATA3D = DATA_REFMESH{ientity} ;
            FFF = fieldnames( DATA_REFMESH{ientity} ) ;
            for ifield = 1:length(FFF)
                MESH3D.SLICES(INDEX).DATA3D.(FFF{ifield}) = DATA_REFMESH{ientity}.(FFF{ifield}) ;
            end
            MESH3D.SLICES(INDEX).DATA3D.CNb = MESH3D.SLICES(INDEX).DATA3D.CONNECTb ;
            
            %  MESH3D.SLICES(INDEX).DATA3D.NAME_SLICE = NAME_SLICE ;
            
        case 'JOINT'
            INDEX = PROPS.INDEX_ENTITY ;
            FFF = fieldnames( DATA_REFMESH{ientity} ) ;
            for ifield = 1:length(FFF)
                MESH3D.JOINTS(INDEX).DATA3D.(FFF{ifield}) = DATA_REFMESH{ientity}.(FFF{ifield}) ;
            end
            % MESH3D.JOINTS(INDEX).DATA3D = DATA_REFMESH{ientity} ;
            MESH3D.JOINTS(INDEX).DATA3D.CNb = MESH3D.JOINTS(INDEX).DATA3D.CONNECTb ;
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% lateral SURFACES
if  DATAIN.DISP3D_lateral == 1
    % Printing lateral surfaces
    for itype = 1:length(DATA_REFMESH)
        MESH1D.PROP(itype).LATERAL_SURFACES.PRINT_ALL =1; % Print all lateral surfaces
    end
else
    for itype = 1:length(DATA_REFMESH)
        MESH1D.PROP(itype).LATERAL_SURFACES.PRINT_ALL =0; % Print all lateral surfaces
    end
    
end
% WRITING MESH FILE
% -----------------------
DATAIN = DefaultField(DATAIN,'ONLY_SHOW_REDUCED_ELEMENTS',0) ; % Option, Dec-17,2019
if DATAIN.ONLY_SHOW_REDUCED_ELEMENTS ==1
    DATAIN.setReducedElements = DATAROM_glo{1}.HROMVAR.setElements ; 
else
    DATAIN.setReducedElements = [] ; 
    
end

DATAIN= DefaultField(DATAIN,'PlotGIDFictitiousInterfaces',0);% 22-Dec-2019



MESH3D_lateral.CONNECTb  = [] ; %DISP3D_lateral.CONNECTb ;
[NameFile_msh,NameFile_res,COOR,CN,NAME_INPUT_DATA,...
    TypeElement,MaterialType,NAMEMESH,DATAIN] = ...
    Construct3DstructureROM(MESH1D,MESH3D,DATAIN,MESH3D_lateral,FOLDER,DATA_REFMESH) ;



IND_ELEM_MESHES = GidMesh2DFE_multi(NameFile_msh,COOR,CN,NAME_INPUT_DATA,MaterialType,...
    TypeElement,NAMEMESH);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
nnode1D = size(MESH1D.COOR,1) ;
nnode3D = size(COOR,1)-nnode1D ;
NODES = {(1:nnode1D)', (1:nnode3D)'+nnode1D};
DATAIN = DefaultField(DATAIN,'PRINT_AVERAGE_STRESSES_ON_ELEMENTS',1) ;
if DATAIN.PRINT_AVERAGE_STRESSES_ON_ELEMENTS ==1
    posgp = cell(size(IND_ELEM_MESHES)) ;
else
    error('Option not implemented')
end

% -------------------
% WRITING .RES FILE
% -------------------
%STRESS3D = STRESS3D(:) ;
strainGLO = [] ;
React = [] ;
RESIDUAL = [] ;
% DISPLACEMENT
% 1D displacement
ndim = size(COOR,2) ;
DISP_1D = zeros(ndim,nnode1D) ;
ndimGLO = length(a)/nnode1D ;
for idim = 1:ndim
    DISP_1D(idim,:) = a(idim:ndimGLO:end) ;
end
%% ROTATION
% ---------
nelem1D = size(DISP_1D,2) ; 
DISP_1D = mat2cell(DISP_1D,ndim,ones(1,nelem1D)) ;
ROTATIONS = mat2cell(MESH1D.ROTATIONSint,ndim,ndim*ones(1,nelem1D)) ;
DISP_1D =  cellfun(@mtimes,ROTATIONS,DISP_1D,'UniformOutput',false) ;  % Transpose
DISP_1D = cell2mat(DISP_1D) ;
  

% DISP3D = DISP3D' ;
DISP3D = [cell2mat(DISP3D')] ;
d = [DISP_1D(:); DISP3D(:)] ; % All displacements

if DATAIN.PlotGIDFictitiousInterfaces == 1
    % Plot fictitious interfaces disp. 
    % --------------------------------
    % 23-Dic-2019 
    dispINTF = [] ; 
    itype = 1; 
    V = DATAROM_glo{itype}.BasisInt; 
     for innode = 1:size(MESH1D.COOR,1) % Loop over 1D nodes
        nSP = size( MESH1D.ROTATIONSint,1) ;      
        ifin = innode*ndimGLO; iini = ifin-ndimGLO+1; 
        aLOC = a(iini:ifin) ; 
        dispINTF = [dispINTF; V*aLOC]; 
        
        
         
        
        
     end
    d = [d; dispINTF]  ; 
     
end



if ~isempty(REACTIONS3D)
    REACTIONS3D = [cell2mat(REACTIONS3D')] ;
    REACTIONS1D = zeros(size(DISP_1D(:))) ;
    DATA.REACTIONS3D = [REACTIONS1D;REACTIONS3D ] ; 
else
    DATA.REACTIONS3D = [] ; 
end

% Forces and Moments (Diagrams)
if ~isempty(GeneralizedForces)
    if ndim == 3
        DATA.Forces1D.AXIAL_FORCE = GeneralizedForces(1,:) ;
        DATA.Forces1D.SHEAR_FORCE_Y = GeneralizedForces(2,:) ;
        DATA.Forces1D.SHEAR_FORCE_Z = GeneralizedForces(3,:) ;
        DATA.Forces1D.TORQUE= GeneralizedForces(4,:) ;
        DATA.Forces1D.BENDING_MOM_Y= GeneralizedForces(5,:) ;
        DATA.Forces1D.BENDING_MOM_Z= GeneralizedForces(6,:) ;
        if size(GeneralizedForces,1) == 7
            DATA.Forces1D.WARPING_BM = GeneralizedForces(7,:) ;
        end
    else
        DATA.Forces1D.AXIAL_FORCE = GeneralizedForces(1,:) ;
        DATA.Forces1D.SHEAR_FORCE_Y = GeneralizedForces(2,:) ;
        DATA.Forces1D.BENDING_MOM_Z= GeneralizedForces(3,:) ;
        
    end
end

DATAIN = DefaultField(DATAIN,'DIMENSIONLESS_ERROR',[]) ; 
if ~isempty(DATAIN.DIMENSIONLESS_ERROR)
    DATAIN = DefaultField(DATAIN,'ShowErrorDisplacementsInPercentage',1) ; 
if DATAIN.ShowErrorDisplacementsInPercentage == 1
   DATA.Forces1D.DispErrorPerc = DATAIN.DIMENSIONLESS_ERROR ; 
else
    
   DATA.Forces1D.DispErrorx1000 = DATAIN.DIMENSIONLESS_ERROR ; 
 
end
end



%%%
DATA.NAMEMESH = NAMEMESH;


DATAIN = DefaultField(DATAIN,'PlotUnified3Dmeshes',1) ;

if   DATAIN.PlotUnified3Dmeshes  == 1
    if ~isempty(STRESSDATA.VONMISES)
        STRESSDATA.VONMISES =  {cell2mat(STRESSDATA.VONMISES)} ;
    end
    if ~isempty(STRESS3D)
        STRESS3D = {cell2mat(STRESS3D')} ;
    end
    
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[NameFileRES ]= GidPostProcess_multi_ROM(COOR,CN,TypeElement,d,strainGLO, STRESS3D, ...
    React,posgp,NameFile_res,MaterialType,NODES,RESIDUAL,DATAIN,DATA,STRESSDATA,IND_ELEM_MESHES,...
    FORCES_2_PRINT,DATA_REFMESH,DATARUN);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
