function GIDprint_BEAM_ROM(MESH1D,DATA_REFMESH,GeneralizedForces,DATAIN,DISP3D,a,DISP3D_lateral,...
    STRESS3D,STRESSDATA,FORCES_2_PRINT)
% Post-process of GID results generated by reduced-order model
% Adapted from Plot3Dstructure.m ;
% and PrintGID1D_3Drepresentation.m
% JAHO, 4-May-2018
if nargin ==0
    load('tmp.mat')
end

MESH3D =[] ;
% Default values
itype = 1;
MESH1D.PROP(itype).INDEX_ENTITY = 1 ;   % Slice/Joint associated to indices "itype"
MESH1D.PROP(itype).TYPE = 'BEAM' ; % JOINT   % Slice associated to indices "itype"
MESH1D.NAME= '1D' ;

MESH1D.PROP(itype).DOMAINSprint.VARIABLES =DATAIN.DOMAINS_POSTPROCESS ;

% MESH1D.PROP(itype).xLOCAL = 1 ;   % Direction assigned by the connectivitites table (default). Other option = -1
% MESH1D.PROP(itype).zLOCAL = {'PLANE',itype,0 };   %
% MESH1D.PROP(itype).DOMAINSprint.INDICES =[1:201] ;  % Number of 3D slices to print (see )
% MESH1D.PROP(itype).DOMAINSprint.TYPE_INDEX ='INDEX_SLICES_LOCAL'  ; %  NUMBER_OF_SLICES/INDEX_SLICES_LOCAL
itypeSLICE = 1 ;
MESH3D.SLICES(itypeSLICE).DATA3D  = DATA_REFMESH ;
MESH3D.SLICES(itypeSLICE).DATA3D.NAME_SLICE  = DATA_REFMESH.NameFileMesh ;
MESH3D.SLICES(itypeSLICE).NEW_COORDINATES = 1 ;
% Defining rotation matrices
[MESH1D.ROTATIONS,MESH1D.ORDER_CONNECTIVITIES] = LocalAxisDefinitionBeams(MESH1D,MESH3D,DATAIN);


% Deciding which beam domains have to be printed
% --------------------------------------------
MESH1D.Elements2Print = WhichBeamElementsToPrint(MESH1D) ;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% How to deal with lateral surfaces ? How to plot it  ? We can think of an
% additional 1D mesh ---the same as the already defined 1D mesh. However,
% we shall not print this 1D mesh ---and we shall not include the
% corresponding coordinates
if  DISP3D_lateral == 1
    
    % Printing lateral surfaces 
    itype = 1; 
    MESH1D.PROP(itype).LATERAL_SURFACES.PRINT_ALL =1; % Print all lateral surfaces 
else
     MESH1D.PROP(itype).LATERAL_SURFACES.PRINT_ALL = 0 ; 
    
end




% WRITING MESH FILE
% -----------------------
MESH3D_lateral.CONNECTb  = [] ; %DISP3D_lateral.CONNECTb ;
[NameFile_msh,NameFile_res,COOR,CN,NAME_INPUT_DATA,...
    TypeElement,MaterialType,NAMEMESH] = Construct3DstructureROM(MESH1D,MESH3D,DATAIN,MESH3D_lateral) ;


IND_ELEM_MESHES = GidMesh2DFE_multi(NameFile_msh,COOR,CN,NAME_INPUT_DATA,MaterialType,TypeElement,NAMEMESH);


%
% disp(['Open GID file  : ']) ;
% disp([NameFile_msh]) ;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

nnode1D = size(MESH1D.COOR,1) ;
nnode3D = size(COOR,1)-nnode1D ;

NODES = {(1:nnode1D)', (1:nnode3D)'+nnode1D};


DATAIN = DefaultField(DATAIN,'PRINT_AVERAGE_STRESSES_ON_ELEMENTS',1) ;

if DATAIN.PRINT_AVERAGE_STRESSES_ON_ELEMENTS ==1
    posgp_3d = [] ;
end
posgp = {[],posgp_3d,[]} ;


% -------------------
% WRITING .RES FILE
% -------------------
%STRESS3D = STRESS3D(:) ;
strainGLO = [] ;
React = [] ;
RESIDUAL = [] ;

% DISPLACEMENT
% 1D displacement
ndim = 3 ;
DISP_1D = zeros(ndim,nnode1D) ;
ndimGLO = length(a)/nnode1D ;
for idim = 1:ndim
    DISP_1D(idim,:) = a(idim:ndimGLO:end) ;
end
% DISP3D = DISP3D' ;
d = [DISP_1D(:); DISP3D(:)] ; % All displacements

% nNODES_PRINT = length(d)/ndim ;
% NODES_PRINT_DISPLACEMENT = 1:nNODES_PRINT ;
% if ~isempty(DISP3D_lateral.VALUE)
%     % d = [d ; DISP3D_lateral.VALUE(:)] ;
%     
% end


DATA.Forces1D.AXIAL_FORCE = GeneralizedForces(1,:) ;
DATA.Forces1D.SHEAR_FORCE_Y = GeneralizedForces(2,:) ;
DATA.Forces1D.SHEAR_FORCE_Z = GeneralizedForces(3,:) ;
DATA.Forces1D.TORQUE= GeneralizedForces(4,:) ;
DATA.Forces1D.BENDING_MOM_Y= GeneralizedForces(5,:) ;
DATA.Forces1D.BENDING_MOM_Z= GeneralizedForces(6,:) ;


DATA.NAMEMESH = NAMEMESH;


 




%%%%%%




GidPostProcess_multi_ROM(COOR,CN,TypeElement,d,strainGLO, STRESS3D, ...
    React,posgp,NameFile_res,MaterialType,NODES,RESIDUAL,DATAIN,DATA,STRESSDATA,IND_ELEM_MESHES,...
    FORCES_2_PRINT,DATA_REFMESH);




% strainGLO =[] ;
%
% React = [] ;NAME_INPUT_DATA = 'Beam1D_3D' ;
% NameFileMesh = '' ;
% DATA.MAXstressVONMISES = MAXstressVONMISES ;
% % Writing results file
% % Nodal vectors
% % -------------------
% NODAL_VECTOR(1).NAME = 'DISPLACEMENTS' ;
% NODAL_VECTOR(1).COMP = {'X-DISP','Y-DISP','Z-DISP'};
% NODAL_VECTOR(1).VAR = d ;
% NODAL_VECTOR(1).NODES = 1:size(COOR,1) ;
% %
% %
% if ~isempty(RESIDUAL.ALL)
%     if DATAINM.FACTOR_MULTIPLY_RESIDUAL_FORCES > 1
%         APPLEG = ['(x',num2str(DATAINM.FACTOR_MULTIPLY_RESIDUAL_FORCES),')'] ;
%     end
%
%
%     NODAL_VECTOR(2).NAME = ['RES.FORCES',APPLEG] ;
%     NODAL_VECTOR(2).COMP = {'X-RES','Y-RES','Z-RES'};
%     NODAL_VECTOR(2).VAR = RESIDUAL.ALL ;
%     NODAL_VECTOR(2).NODES = NODES{2}' ;
% end
%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% % Scalar vectors: forces and moments
% DATA = DefaultField(DATA,'Forces1D',[]) ;
% NODAL_SCALAR = [] ; iacum = 1 ;
% if ~isempty(DATA.Forces1D)
%      if DATAINM.FACTOR_MULTIPLY_MOMENTS_DIAGRAM > 1
%         APPLEG = ['(x',num2str(DATAINM.FACTOR_MULTIPLY_MOMENTS_DIAGRAM),')'] ;
%     end
%
%     fff = fieldnames(DATA.Forces1D) ;
%     for ifield = 1:length(fff)
%         FORCE = DATA.Forces1D.(fff{ifield}) ;
%         if ~isempty(FORCE)
%             NODAL_SCALAR(iacum).NAME = [fff{ifield},APPLEG ];
%             NODAL_SCALAR(iacum).VAR = FORCE ;
%             NODAL_SCALAR(iacum).NODES = NODES{1} ;
%             iacum = iacum + 1;
%         end
%     end
% end
% % scalar defined on GAUSS POINTS, mesh 1
% imesh = 1 ;
% MESH(imesh).TypeElement = TypeElement{imesh} ;
% MESH(imesh).posgp = posgp{imesh} ;
% MESH(imesh).NAMEMESH = DATA.NAMEMESH{imesh};
% MESH(imesh).GAUSS_SCALAR(1).NAME = 'Max.Von_Mises' ;
% MESH(imesh).GAUSS_SCALAR(1).VAR = DATA.MAXstressVONMISES ;
% MESH(imesh).GAUSS_SCALAR(1).ELEMENTS = IND_ELEM_MESHES{imesh} ;
%
% if ~isempty(RESIDUAL.MAX_NORM)
%      if DATAINM.FACTOR_MULTIPLY_RESIDUAL_FORCES > 1
%         APPLEG = ['(x',num2str(DATAINM.FACTOR_MULTIPLY_RESIDUAL_FORCES),')'] ;
%     end
% MESH(imesh).GAUSS_SCALAR(2).NAME = ['RESIDF_Max_Norm',APPLEG] ;
% MESH(imesh).GAUSS_SCALAR(2).VAR = RESIDUAL.MAX_NORM ;
% MESH(imesh).GAUSS_SCALAR(2).ELEMENTS = IND_ELEM_MESHES{imesh} ;
% MESH(imesh).GAUSS_SCALAR(3).NAME = ['RESIDF_Norm_Avg',APPLEG] ;
% MESH(imesh).GAUSS_SCALAR(3).VAR = RESIDUAL.NORM_AVERAGE ;
% MESH(imesh).GAUSS_SCALAR(3).ELEMENTS = IND_ELEM_MESHES{imesh} ;
% end
%
%
%
% imesh = 2;
% MESH(imesh).TypeElement = TypeElement{imesh} ;
% MESH(imesh).posgp = posgp{imesh} ;
% MESH(imesh).NAMEMESH = DATA.NAMEMESH{imesh};
% MESH(imesh).GAUSS_SCALAR(1).NAME = 'Von_Mises' ;
% MESH(imesh).GAUSS_SCALAR(1).VAR = DATA.stressVONMISES ;
% MESH(imesh).GAUSS_SCALAR(1).ELEMENTS = IND_ELEM_MESHES{imesh} ;
% %
% MESH(imesh).GAUSS_MATRIX(1).NAME = 'STRESS' ;
% MESH(imesh).GAUSS_MATRIX(1).VAR = stressGLO ;
% MESH(imesh).GAUSS_MATRIX(1).COMP = {'Stress-xx','Stress-yy','Stress-zz','Stress-xy','Stress-yz','Stress-xz'}  ;
% MESH(imesh).GAUSS_MATRIX(1).ELEMENTS = IND_ELEM_MESHES{imesh} ;
%
% nelemE(1) = size(CN{1},2) ;
% nelemE(2) = size(CN{2},2) ;
% ndim = size(COOR,2) ;
%
% GidResults2DFE_multi(NameFile_res,ndim,TypeElement,NODAL_VECTOR,NODAL_SCALAR,MESH,posgp);
%
% cddd = cd ;
% NAMEFILEOPEN =  [cddd,filesep,NameFile_res] ;
% NAMEMESH = [cddd,filesep,NameFile_msh] ;
%
% %  if DATA.COMPRESS_GID == 1
% %     disp('Compressing GID FILE ...')
% %     TEXT = ['gid -PostResultsToBinary  ',NAMEFILEOPEN, ' ',NAMEFILEOPEN] ;
% %     unix(TEXT) ;
% %     delete(NameFile_msh)
% %     disp('Done')
% % end
%
%
% disp('open GID FILE:')
% clipboard('copy',NAMEFILEOPEN)
% disp(NAMEFILEOPEN)
%
% DATA = DefaultField(DATA,'OPEN_GID',0) ;
% if DATA.OPEN_GID ==1
%     TTTT = ['gidpost ',NAMEFILEOPEN] ;
%     unix(TTTT);
% end