function [NAMEPROJECTS,NAME_PROJ_LOC,NUMBER_OF_DOMAINS,IMPOSED_DISP,BoundaryConditions,GENERALIZED_FORCES_ENDS_BEAM] ...
    = NameProjectsBeam(NUMBER_OF_SLICES,NAME_ROOT_FE_BEAM,PRESCRIBED_VALUE,DATARUN)

DATARUN = DefaultField(DATARUN,'TYPE_BOUNDARY_CONDITIONS','PERIODIC_BEAMS_MASS_MATRIX') ;
 
DATARUN = DefaultField(DATARUN,'TYPE_TRAINING','STANDARD_6tests') ;
switch DATARUN.TYPE_BOUNDARY_CONDITIONS 
    case 'PERIODIC_WITH_WARPING'
        DATARUN.TYPE_TRAINING = 'STANDARD_8tests' ; 
end

GENERALIZED_FORCES_ENDS_BEAM=[] ; 
switch DATARUN.TYPE_TRAINING
    case 'STANDARD_6tests'
        [NAMEPROJECTS,NAME_PROJ_LOC,NUMBER_OF_DOMAINS,IMPOSED_DISP,BoundaryConditions] ...
            = NPROJ3D_normal(NUMBER_OF_SLICES,NAME_ROOT_FE_BEAM,PRESCRIBED_VALUE,DATARUN) ;
         case 'STANDARD_8tests'
        [NAMEPROJECTS,NAME_PROJ_LOC,NUMBER_OF_DOMAINS,IMPOSED_DISP,BoundaryConditions] ...
            = NPROJ3D_normal8tests(NUMBER_OF_SLICES,NAME_ROOT_FE_BEAM,PRESCRIBED_VALUE,DATARUN) ;
    case 'FORCES_4tests'
        [NAMEPROJECTS,NAME_PROJ_LOC,NUMBER_OF_DOMAINS,IMPOSED_DISP,BoundaryConditions,GENERALIZED_FORCES_ENDS_BEAM] ...
            = NPROJ3D_4testFORCE(NUMBER_OF_SLICES,NAME_ROOT_FE_BEAM,PRESCRIBED_VALUE,DATARUN) ;  
    case 'NONE'
        NAMEPROJECTS = [] ;
        NAME_PROJ_LOC = [] ;
        NUMBER_OF_DOMAINS = [] ;
        IMPOSED_DISP = [] ;
        BoundaryConditions = [] ;
    case 'ONE_TEST'
        error('This option  proved to be quite unreliable')
        [NAMEPROJECTS,NAME_PROJ_LOC,NUMBER_OF_DOMAINS,IMPOSED_DISP,BoundaryConditions,GENERALIZED_FORCES_ENDS_BEAM] ...
            = NPROJ3D_onetest(NUMBER_OF_SLICES,NAME_ROOT_FE_BEAM,PRESCRIBED_VALUE,DATARUN) ;
    otherwise
        
        error('Option not implemented')
        
end

