function [VAR,CONVERGED,DATA] = NewtonRapshonStaticLarge(DATA,OPERFE,VAR,MATPRO,DOFl)
% ---------------------------------------------------------------------------------------------------
% FUNCTION: NewtonRapshonStaticLarge
% ---------------------------------------------------------------------------------------------------
% PURPOSE:
%   Performs a Newton–Raphson iterative scheme for solving nonlinear static or dynamic finite element
%   problems. It computes displacements, internal forces, stress measures (Cauchy, Von Mises), and 
%   optionally dynamic quantities (velocity and acceleration) depending on the model setup.
%
% USAGE:
%   [VAR, CONVERGED, DATA] = NewtonRapshonStaticLarge(DATA, OPERFE, VAR, MATPRO, DOFl)
%
% INPUTS:
%   - DATA     : Structure with all solver settings, flags (e.g., dynamic, small strain),
%                tolerances, time integration parameters, and options for ROM or hydro forces.
%   - OPERFE   : Structure containing assembled FE operators (connectivity, shape functions,
%                boundary condition mappings, hydrostatic terms, etc.).
%   - VAR      : Structure containing all the current solution variables (displacements, internal vars,
%                forces, stresses, etc.). Also holds external forces.
%   - MATPRO   : Material property structure (e.g., elasticity tensors, constitutive parameters).
%   - DOFl     : Indices of the active degrees of freedom (i.e., not constrained).
%
% OUTPUTS:
%   - VAR        : Updated structure with converged solution fields.
%   - CONVERGED  : Convergence flag (1 if converged, 0 if not).
%   - DATA       : Updated DATA structure with residuals, energy snapshots, and iteration history.
%
% FUNCTIONALITY:
%   - Assembles residual and stiffness matrix based on current solution state.
%   - Handles both static and dynamic problems via generalized-alpha or other integration.
%   - Optionally includes hydrostatic pressure forces (e.g., for floating body simulations).
%   - Handles affine (periodic or reduced) boundary conditions via DOFm/DOFr mapping.
%   - Checks convergence using a norm-based criterion on the residual vector.
%   - Computes stresses and internal energies once converged.
%
% SPECIAL FEATURES:
%   - Compatible with reduced-order modeling frameworks.
%   - Allows skipping failed iterations (e.g., if negative Jacobian is encountered).
%   - Modular dynamic and hydrostatic extensions included.
%   - Affine mapping support (for periodic or reduced models).
%
% NOTES:
%   - Requires `ResidualFromDisplacementsVAR`, `GetStiffnessMatrix`, `VonMisesCauchyStresses`,
%     and several helper functions (`CheckConvergenceLSTR`, `UpdateVelocityAcceleration`, etc.).
%   - Make sure `DATA.NEWTON_RAPHSON.NMAXiter` and convergence criteria are well configured.
%
% AUTHOR:
%   Joaquín A. Hernández, UPC – CIMNE
%   Date: 09-Feb-2022 (last major update for residual restructuring)
%   Comments generated by ChatGPT-4, 12-May-2025
% DEPENDENCIES:
%   - ResidualFromDisplacementsVAR
%   - GetStiffnessMatrix
%   - CheckConvergenceLSTR
%   - VonMisesCauchyStresses
%   - KineticAndStrainEnergyGet
%   - UpdateVelocityAcceleration
%   - ResidualDynamicPart (optional)
%   - PressureForcesFromDisplacements (optional)
%
%

if nargin == 0
    load('tmp3.mat')
end

kiter = 1;
CONVERGED = 0 ;
normd = 1e20 ;
% Internal variables (value at previous time step)
% ----------------------
VARint_n = [];
if ~isempty(DATA.ListFieldInternalVariables)
    for iINTVAR = 1:length(DATA.ListFieldInternalVariables)
        NameIntVar= DATA.ListFieldInternalVariables{iINTVAR} ;
        VARint_n.(NameIntVar) = VAR.(NameIntVar) ;
    end
end


while  kiter <=DATA.NEWTON_RAPHSON.NMAXiter
    
    % Residual forces from displacements  (STATIC )
    % Before 9-Feb-2022
    %     [VAR.GLSTRAINS,VAR.PK2STRESS,celastST,VAR.RESID,Fint,FgradST,VAR.PK1STRESS,detFgrad] =...
    %         ResidualFromDisplacements(OPERFE,VAR.DISP,MATPRO,DATA,VAR.FEXT) ;%
    % After 9-Feb-2022
    DATA.kiter = kiter;
    [VAR,celastST,FgradST,detFgrad] =  ResidualFromDisplacementsVAR(OPERFE,VAR,MATPRO,DATA,VARint_n) ;
    
    if DATA.ISDYNAMIC == 1 && ~isempty(VAR.RESID)
        % Dynamic part of the residual
        VAR =  ResidualDynamicPart(VAR,OPERFE,DATA.TIME_INTEGRATION_PARAMETERS,DATA.DeltaT) ;
    end
    if ~isempty(OPERFE.HYDRO)
        % Hydrostatic forces
        % \FextPR{}{}   = - \NbST{T}  \wSTft{}  \tPRESSst}
        % See /home/joaquin/Desktop/CURRENT_TASKS/MATLAB_CODES/DEVELOPMENTS/DynamicFloatingBodies.tex
        % ------------------------
        [VAR.FEXTpress,VAR.tPRESS,kPRESSst ]= PressureForcesFromDisplacements(DATA,OPERFE,VAR) ;
        VAR.RESID = VAR.RESID - VAR.FEXTpress ;
        VAR_FEXT_DOFl = VAR.FEXT(DOFl) + VAR.FEXTpress(DOFl);
    else
        VAR_FEXT_DOFl = VAR.FEXT(DOFl) ;
    end
    
    % Update snapshots of iterative results
    DATA = UpdateIterativeSnapshot(DATA,VAR,1+kiter) ;
    
    if isempty(celastST) && DATA.INTERNAL_FORCES_USING_precomputed_Kstiff == 0
        disp('Not converged ..., because of Negative JAcobians (you may disable this by setting PROCEED_WITH_NEGATIVE_JACOBIANS=1)')
        DATA = ReshapeIterativeSnapshot(DATA,VAR,kiter) ;
        break
    else
        % 7. Check convergence
        if isempty(OPERFE.DOFm)
            VAR_FINT_DOFL = VAR.FINT(DOFl) ;
            VAR_RESID_DOFL = VAR.RESID(DOFl) ;
        else
            % See /home/joaquin/Desktop/CURRENT_TASKS/MATLAB_CODES/TESTING_PROBLEMS_FEHROM/104_EIFEM_plast2D/10_PeriodicQUADL.mlx
            VAR_FINT_DOFL = OPERFE.A'*VAR.FINT ;
            VAR_RESID_DOFL = OPERFE.A'*VAR.RESID ;
        end
        [~, ~,CONVERGED]=  CheckConvergenceLSTR(VAR_FINT_DOFL,VAR_FEXT_DOFl,VAR_RESID_DOFL,kiter,normd,DATA) ;
        
        
        if CONVERGED == 1  
            
            if VAR.NEGATIVE_JACOBIANS
                % Introduced on Sept- 30th 2025
                warning('Converged with negative jacobians')
                CONVERGED = 0 ; 
                kiter = 10* DATA.NEWTON_RAPHSON.NMAXiter; 
            end
            % Compute Von Mises Stress
            if DATA.SMALL_STRAIN_KINEMATICS == 0
                PK1STRESS_forCauchy  = VAR.PK1STRESS ;
            else
                PK1STRESS_forCauchy  = VAR.PK2STRESS ;
            end
            [ VAR.VONMISES_CAUCHY_STRESS,VAR.CAUCHY_STRESS ]= ...
                VonMisesCauchyStresses(PK1STRESS_forCauchy,FgradST,DATA.MESH.ndim,detFgrad,DATA) ;
            if DATA.ISDYNAMIC == 1
                % Update velocities and accelerations
                VAR =  UpdateVelocityAcceleration(VAR,DATA.TIME_INTEGRATION_PARAMETERS,DATA.DeltaT) ;
                %  VAR = KineticAndStrainEnergyGet(VAR,OPERFE,DATA,MATPRO) ;
                %   6-May-2023
                %
            end
            VAR = KineticAndStrainEnergyGet(VAR,OPERFE,DATA,FgradST) ;  % 6-May-2023
            break
        else
            %  Updating d_l by solving  Delta_d_L =  -K(DOFl,DOFl)\Res(DOFl)
            % 8. Assembly Stiffness Matrix (static part)
            
            K = GetStiffnessMatrix(OPERFE,DATA,VAR,FgradST,celastST) ;
            if DATA.ISDYNAMIC == 1
                % Dynamic part of the Jacobian
                K  =  KstifflDynamicPart(VAR,OPERFE,DATA.TIME_INTEGRATION_PARAMETERS,DATA.DeltaT,K) ;
            end
            
            if ~isempty(OPERFE.HYDRO)
                % Contribution of hydrostatic forces
                % \FextPR{}{}   = - \NbST{T}  \wSTft{}
                % diag(kPRESSst)*Lbool
                % See /home/joaquin/Desktop/CURRENT_TASKS/MATLAB_CODES/DEVELOPMENTS/DynamicFloatingBodies.tex
                % ------------------------
                K = K - OPERFE.HYDRO.NbST_w'*(ConvertBlockDiag_general(kPRESSst,DATA.MESH.ndim,OPERFE.HYDRO.irowsNDIM,OPERFE.HYDRO.icolsNDIM)*OPERFE.HYDRO.Lbool) ;
            end
            
            if isempty(OPERFE.DOFm)
                if DATA.SOLVER_IS_ITERATIVE == 1
                    tolCONJG =[] ;
                    niterCONJG =[] ;
                    delta_dL=    pcg(K(DOFl,DOFl),-VAR.RESID(DOFl),[],[]) ;
                else
                    delta_dL = -K(DOFl,DOFl)\VAR.RESID(DOFl);
                    
%                     disp('borrar esto')
%                     opts = struct('tol', 1e-10, 'maxit', 10000);
%                     ddd = eigs(K(DOFl,DOFl), 10, 'smallestabs', opts);
%                     disp(['Smallest EIG = ',num2str(ddd(1))])
%                     if ddd(1)<= 0
%                         disp('BUCKLING')
%                         ddd
%                     end
%                     
% 
% %                     [EEE,VVV] =  eig(full(K(DOFl,DOFl))); 
% %                     VVV = diag(VVV) ; 
% %                     VVV_smallest =VVV(end); 
% %                     disp('---------------------------')
%                     
                    
                end
                VAR.DISP(DOFl) =  VAR.DISP(DOFl) + delta_dL ;
                normd = norm(delta_dL) ;
                
            else
                % Affine boundary conditions
                % See /home/joaquin/Desktop/CURRENT_TASKS/MATLAB_CODES/TESTING_PROBLEMS_FEHROM/104_EIFEM_plast2D/10_PeriodicQUADL.mlx
                if DATA.SOLVER_IS_ITERATIVE == 1
                    tolCONJG =[] ;
                    niterCONJG =[] ;
                    delta_dL=    pcg(OPERFE.A'*(K*OPERFE.A),-VAR.RESID(DOFl),[],[]) ;
                else
                    delta_dL = -(OPERFE.A'*(K*OPERFE.A))\(OPERFE.A'*VAR.RESID);
                end
                VAR.DISP(DOFl) =  VAR.DISP(DOFl) + delta_dL ;
                VAR.DISP(OPERFE.DOFr) =  OPERFE.G*VAR.DISP(OPERFE.DOFm) + OPERFE.uBAR ;
                
                
                normd = norm(delta_dL) ;
                
                
                
            end
            
            
            
        end
        kiter = kiter + 1;
    end
end