function GIDprint_PLATE_ROM(MESH2D,DATA_REFMESH,GeneralizedForces,DATAIN,DISP3D,a,DISP3D_lateral,...
    STRESS3D,STRESSDATA,FORCES_2_PRINT,MESH3D,FOLDER,DATARUN)
% Post-process of GID results generated by reduced-order model
% Adapted from Plot3Dstructure.m ;
% and PrintGID1D_3Drepresentation.m, and GIDprint_BEAB_ROMslice.m
% JAHO, 4-May-2018/5-July-2018/25-July-2018
if nargin ==0
    load('tmp0.mat')
end
% 3D mesh DATA --> DATA_REFMESH
for ientity = 1:length(DATA_REFMESH)
    PROPS = MESH2D.PROP(ientity) ;
    switch PROPS.TYPE
        case 'RVE'
            INDEX = PROPS.INDEX_ENTITY ;
            %      NAME_SLICE = MESH3D.RVES(INDEX).DATA3D.NAME_SLICE 
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %   MESH3D.RVES(INDEX).DATA3D = DATA_REFMESH{ientity} ;
          %  OLD_CONN = MESH3D.RVES(INDEX).DATA3D.CNb ; 
            FFF = fieldnames( DATA_REFMESH{ientity} ) ;
            for ifield = 1:length(FFF)
                MESH3D.RVES(INDEX).DATA3D.(FFF{ifield}) = DATA_REFMESH{ientity}.(FFF{ifield}) ;
            end
            MESH3D.RVES(INDEX).DATA3D.CNb = MESH3D.RVES(INDEX).DATA3D.CONNECTb ;
            
            %  MESH3D.RVES(INDEX).DATA3D.NAME_SLICE = NAME_SLICE ;
            
        otherwise 
            error('Option not implemented ')
    end    
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% lateral SURFACES
if  DATAIN.DISP3D_lateral == 1
    % Printing lateral surfaces
    for itype = 1:length(DATA_REFMESH)
        MESH2D.PROP(itype).LATERAL_SURFACES.PRINT_ALL =1; % Print all lateral surfaces
    end
else
    for itype = 1:length(DATA_REFMESH)
        MESH2D.PROP(itype).LATERAL_SURFACES.PRINT_ALL =0; % Print all lateral surfaces
    end
    
end
% WRITING MESH FILE
% -----------------------
MESH3D_lateral.CONNECTb  = [] ; %DISP3D_lateral.CONNECTb ;
[NameFile_msh,NameFile_res,COOR,CN,NAME_INPUT_DATA,...
    TypeElement,MaterialType,NAMEMESH,DATAIN] = Construct3DstructureROMplate(MESH2D,MESH3D,DATAIN,MESH3D_lateral,FOLDER) ;


IND_ELEM_MESHES = GidMesh2DFE_multi(NameFile_msh,COOR,CN,NAME_INPUT_DATA,MaterialType,TypeElement,NAMEMESH);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
nnode2D = size(MESH2D.COORvert,1) ;
nnode3D = size(COOR,1)-nnode2D ;
NODES = {(1:nnode2D)', (1:nnode3D)'+nnode2D};
DATAIN = DefaultField(DATAIN,'PRINT_AVERAGE_STRESSES_ON_ELEMENTS',1) ;
if DATAIN.PRINT_AVERAGE_STRESSES_ON_ELEMENTS ==1
   posgp = cell(size(IND_ELEM_MESHES)) ; 
else
    error('Option not implemented')
end

% -------------------
% WRITING .RES FILE
% -------------------
%STRESS3D = STRESS3D(:) ;
strainGLO = [] ;
React = [] ;
RESIDUAL = [] ;
% DISPLACEMENT
% 1D displacement
ndim = 3 ;
DISP_2D = zeros(ndim,nnode2D) ;
DATAIN = DefaultField(DATAIN,'PLOT_2D_RESULTS',1) ; 
 

if  DATAIN.PLOT_2D_RESULTS== 1 ;
         aCOL = reshape(a,[],nnode2D) ; 

   DISP_2D =  aCOL(1:ndim,:); 
%     for idim = 1:ndim
%         DISP_2D(idim,:) = a(idim:ndimGLO:end) ;
%     end
end
% DISP3D = DISP3D' ;
DISP3D = [cell2mat(DISP3D')] ;
d = [DISP_2D(:); DISP3D(:)] ; % All displacements
%Forces and Moments (Diagrams)
DATA.GeneralizedForces = GeneralizedForces ;  
%%
DATA.NAMEMESH = NAMEMESH;


DATAIN = DefaultField(DATAIN,'PlotUnified3Dmeshes',1) ;

if   DATAIN.PlotUnified3Dmeshes  == 1
    if ~isempty(STRESSDATA.VONMISES)
        STRESSDATA.VONMISES =  {cell2mat(STRESSDATA.VONMISES)} ;
    end
    if ~isempty(STRESS3D)
        STRESS3D = {cell2mat(STRESS3D')} ; 
    end
    
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
GidPostProcess_multi_ROM(COOR,CN,TypeElement,d,strainGLO, STRESS3D, ...
    React,posgp,NameFile_res,MaterialType,NODES,RESIDUAL,DATAIN,DATA,STRESSDATA,IND_ELEM_MESHES,...
    FORCES_2_PRINT,DATA_REFMESH,DATARUN);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

end 


function DISP2D= Determine2DfieldsRVE(a,MESH2D)  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% a --> Displacement midside points of each quadrilateral element 
% MESH2D --> Created in function Geometry2Dstructure.m 
% Quadrilateral element determined by four planes x=xmin, x=xmax, y=ymin, y=ymax 
% Midside points corresponds to columns 5 to 8 in CN, are numbered in the following order 
% NODE 1 (5)  = plane x=xmin;  NODE 2 (6)= plane y=ymin, NODE 3 (7) = plane x=xmax, NODE 4 (8) = plane y=ymax 
%
% % Corner points, on the other hand, are labelled as 
% NODE 1 = planes (xmin,ymax), NODE 2 = planes (xmin,yin), NODE 3 = planes
% (xmax,ymin), NODE 4 = planes (xmax,ymax )
%
% The vector of displacement "a" corresponds to the generalized
% displacements of the midside points 
% This function computes, by interpolation, an estimation of the
% displacement of the remaining nodes (corner points)
% JAHO, 26-July-2018
% ---------------------------------------------------------------
ndimGLO = length(a)/size(MESH2D.COOR,1) ;
 ndim = 3 ; 
 nrigidbody = 6 ; 
a = reshape(a,ndimGLO,[]) ; 
a = a(1:nrigidbody,:) ;  % Generalized displacements (midside points)
nnode = size(MESH2D.COORall,1) ; % Number of nodes (quadratic mesh)
DISP2D = zeros(nnode,ndim) ; % Required output (displacement all nodes quadratic mesh )

NODES_MIDSIDE = MESH2D.NODESmid ;  % Global numbering of midside points 
DISP2D(NODES_MIDSIDE,:) =a(1:ndim,:)'; % Translational displacements (midside points)

% ------------------------------
% DISPLACEMENTS CORNER POINTS (computed element-wise)
% ----------------------------
% --------------
imidside = {[4, 1],[1,2],[2,3],[3,4] };
d = cell(size(imidside)); % Displacements 
NODES_VERTEX = cell(size(imidside)); % Displacements 
for ipoint = 1:length(imidside) % Loop over corner points
    [d{ipoint},NODES_VERTEX{ipoint}]= EstimationDisplacementCornerGLO(MESH2D,ipoint,imidside{ipoint},a) ;
end

% Next we perform a loop over all elements 
NODESvert = MESH2D.NODESvert ; 
DISP_CORNERS = zeros(nnode,ndim) ;
NODES_VISITED = zeros(nnode,1) ; 
for inode = 1:length(NODESvert)
    node = NODESvert(inode) ;  
    for ivertices = 1:length(NODES_VERTEX)
       III =  find(NODES_VERTEX{ivertices}==node) ;
       if ~isempty(III)
           DISP_CORNERS(node,:) = DISP_CORNERS(node,:) + d{ivertices}(:,III)' ; 
           NODES_VISITED(node) = NODES_VISITED(node) + +1; 
       end
    end
end

for idim  =1:ndim 
    DISP_CORNERS(NODESvert,idim) = DISP_CORNERS(NODESvert,idim)./ NODES_VISITED(NODESvert) ;
end

 
DISP2D(NODESvert,:) = DISP_CORNERS(NODESvert,:) ; 

DISP2D = DISP2D' ; 


end

function d = EstimationDisplacementCorner(MESH2D,a,imidside1,COORcorner)

% Generalized displacement midside points plane 
NODES_mid = MESH2D.CN(:,imidside1) ; 
aMIDSIDE = a(:,NODES_mid) ; 
% Coordinates midside points
COORmids = MESH2D.COOR(NODES_mid(1),1) ;
% Relative coordinates 
COORrel = COORmids-COORcorner ; 
% Rigid body modes 
R = ConstructBasisRigidBody(COORrel) ;
% Displacement estimated by superposing translation  and rotation 
d = R*aMIDSIDE ; 

end

function  [d,NODES]= EstimationDisplacementCornerGLO(MESH2D,ipoint,imidside,a)

NODES = MESH2D.CNall(:,ipoint) ;  % Global numbering  corner points "ipoint"
COORcorner = MESH2D.COORall(NODES(1),:) ;       % Coordinates of one of such points
% 1) ESTIMATION DISPLACEMENT USING INFORMATION PLANE xmin
d1 = EstimationDisplacementCorner(MESH2D,a,imidside(1),COORcorner) ; 
% 22) ESTIMATION DISPLACEMENT USING INFORMATION PLANE ymax
d4 = EstimationDisplacementCorner(MESH2D,a,imidside(2),COORcorner) ; 
% Average 
d = (d1+d4)/2 ;

end
