
%load('tmp1.mat')
DATAcoarsefine = [] ;
% INPUTS_LOC = DefaultField(INPUTS_LOC,'FACTOR_PERIODICITY',1) ;
% beta_p = INPUTS_LOC.FACTOR_PERIODICITY ;
PRESCRIBED_VALUES  = INPUTS_LOC.DISPLACEMENTS_RIGID_BODY ; % Rigid body amplitudes face 1
NAMEPROJECT  = INPUTS_LOC.NAMEPROJECT ; % Rigid body amplitudes face 1


[Gb,dR,DOFr,DOFm] = PRESCRIBED_DISP_PLATES_RVE_fun(PRESCRIBED_VALUES,NAMEPROJECT,DOMAINVAR,COOR,CONNECTb,TypeElementB,DATA) ;
