function [f,gradf] = objfungrad(x)
f = -x(11);
% Gradient of the objective function:

    gradf = [ 0,... 
              0,... 
              0,... 
              0,... 
              0,... 
              0,... 
              0,... 
              0,... 
              0,... 
              0,... 
              0,... 
              0,... 
              -1,... 
              0];

end
