function [ statesdot, j_statesdot ] = mb_fm_mex_source_zermelo(states, controls)
%mb_fm_mex_source_zermelo
% File automatically generated by FALCON.m

%=== Extract Data From Input ==============================================
x = states(1);
y = states(2);
u = controls(1);

%=== Jacobians and Hessians ===============================================
j_states = zeros(2, 3);
j_states(:, 1 : 2) = eye(2);
j_x = j_states(1, :);
j_y = j_states(2, :);
j_controls = zeros(1, 3);
j_controls(:, 3 : 3) = eye(1);
j_u = j_controls(1, :);

%=== Write Constants ======================================================

%=== Subsystem source_zermelo =============================================

% Defined at ?

% Call sys_398ef064917340965807c0c11f1a7ead_jac
[ statedottmp, j_statedottmp ] = sys_398ef064917340965807c0c11f1a7ead_jac(states, controls);

% Hessian Jacobian for sys_398ef064917340965807c0c11f1a7ead_jac
tmp_j_input_sys_398ef064917340965807c0c11f1a7ead_jac = [j_states; j_controls];

% Calculation of Jacobian with respect to function global input for sys_398ef064917340965807c0c11f1a7ead_jac
j_statedottmp = j_statedottmp * tmp_j_input_sys_398ef064917340965807c0c11f1a7ead_jac;

% Combine Variables to statesdot
statesdot = [statedottmp];
j_statesdot = [
    j_statedottmp(1, :)
    j_statedottmp(2, :)
];

end
