function [out1,j_out1,h_out1] = sys_398ef064917340965807c0c11f1a7ead_jac(in1,in2val1)
%SYS_398EF064917340965807C0C11F1A7EAD_JAC
%    [OUT1,J_OUT1,H_OUT1] = SYS_398EF064917340965807C0C11F1A7EAD_JAC(IN1,IN2VAL1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-May-2025 01:35:10

%Generated using CreateGradient
%Input dimensions : {[2 1], [1 1]}
%Derivative inputs: [true true]
%DerivativeOrder  : 1
%Output dimensions: {[2 1]}
%Constant outputs : false
in1val2 = in1(2,:);
out1 = [in1val2./2.0+cos(in2val1).*3.0e+1;sin(in2val1).*3.0e+1];
if nargout > 1
    j_out1 = reshape([0.0,0.0,1.0./2.0,0.0,sin(in2val1).*-3.0e+1,cos(in2val1).*3.0e+1],[2,3]);
end
if nargout > 2
    h_out1 = zeros(0,0);
end
end
